#!/usr/bin/env python3
"""Build the 10-app Support/Helpdesk capture from inspected first-party pages.

Search snippets are retained only as query traces; evidence entries below cite
opened pages. This script does not call a search provider or an LLM.
"""
from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TODAY = "2026-09-24"
STAMP = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def ev(field, claim, url, title, source_type, observation, support="supports"):
    return {
        "claim": claim,
        "field": field,
        "source_url": url,
        "source_title": title,
        "source_type": source_type,
        "accessed_at": TODAY,
        "support": support,
        "excerpt_or_observation": observation,
    }


def src(title, url, observation, retrieval="fetch_page"):
    return {"title": title, "url": url, "retrieval": retrieval, "observation": observation}


def rec(app_id, app, website_hint, description, auth_status, auth_methods,
        self_serve_status, self_serve_details, credential_status, credential_path,
        credential_gate, api_available, api_types, api_breadth, api_details,
        mcp_status, mcp_details, mcp_scope, build_verdict, build_blocker,
        build_rationale, evidence, confidence, limitations, researcher_notes,
        source_conflicts=None):
    return {
        "schema_version": "1.0",
        "app_id": app_id,
        "app": app,
        "category": "Support and Helpdesk",
        "website_hint": website_hint,
        "description": description,
        "auth_status": auth_status,
        "auth_methods": auth_methods,
        "self_serve_status": self_serve_status,
        "self_serve_details": self_serve_details,
        "credential_access": {
            "status": credential_status,
            "path": credential_path,
            "plan_or_gate": credential_gate,
        },
        "api": {
            "available": api_available,
            "types": api_types,
            "breadth": api_breadth,
            "details": api_details,
        },
        "mcp": {
            "status": mcp_status,
            "details": mcp_details,
            "search_scope": mcp_scope,
        },
        "buildability": {
            "verdict": build_verdict,
            "blocker": build_blocker,
            "rationale": build_rationale,
        },
        "evidence": evidence,
        "confidence": confidence,
        "research_timestamp": STAMP,
        "research_status": "COMPLETE",
        "verification_status": "NOT_CHECKED",
        "source_conflicts": source_conflicts or [],
        "limitations": limitations,
        "researcher_notes": researcher_notes,
    }


records = [
    rec(
        11, "Zendesk", "http://zendesk.com/",
        "Customer-service platform with Support ticketing for tickets, users, organizations, custom objects, and ticket workflows.",
        "CONFIRMED", ["OAuth 2.0", "Bearer/token", "API key", "Basic"],
        "SELF_SERVE_WITH_RESTRICTIONS",
        "Zendesk lists self-serve trials and paid Support/Suite plans. API requests require a verified user; OAuth access is instance-bound, while public multi-customer integrations must use a global OAuth client. The opened pricing page does not map API access to a specific trial or plan, so a free-credential conclusion is not assigned.",
        "RESTRICTED",
        "Use a verified Zendesk user and an OAuth client/token for the target instance. Zendesk API tokens can be managed in Admin Center, but the official guide marks them deprecated; multi-customer apps must use a global OAuth token.",
        "Verified user and account authorization are required. Regular instance OAuth is not sufficient for a public multi-customer integration; the developer terms require global OAuth. API tokens are deprecated and use Basic authentication.",
        "YES", ["REST"], "BROAD",
        "The official Support/Ticketing API covers tickets, users, organizations, custom objects, and ticket workflows with standard REST resources. Rate limits and certain advanced entitlements are account/endpoint dependent; this assessment does not infer MCP from the REST API.",
        "UNKNOWN",
        "No first-party Zendesk MCP server was established in the reviewed material. This is an unresolved field, not a NOT_FOUND claim.",
        "Targeted search of developer.zendesk.com for Zendesk MCP returned no results; opened the official security/auth and Support Ticketing API references. No comprehensive Zendesk-owned repository, marketplace, or all-product documentation audit was performed, so status remains UNKNOWN.",
        "BUILDABLE_WITH_CONSTRAINTS",
        "Verified account access and OAuth client setup are required; public distribution requires global OAuth. Plan-to-API entitlement and official MCP availability remain unresolved.",
        "A broad official REST API supports core support actions, but the required verified-user/OAuth setup and global OAuth rule for multi-customer distribution add material constraints.",
        [
            ev("description", "Zendesk positions its product as an AI customer-service platform with ticketing and support plans.", "https://www.zendesk.com/pricing/", "Zendesk Pricing Plans | Starting from $19/month", "official_pricing", "Opened pricing page describes the customer-service solution and lists Support ticketing and Suite service plans."),
            ev("auth", "Zendesk API supports OAuth access tokens sent as Bearer tokens; API tokens are a separate deprecated Basic-auth method.", "https://developer.zendesk.com/api-reference/introduction/security-and-auth/", "Security and authentication | Zendesk Developer Docs", "official_auth_docs", "Official page documents OAuth Bearer requests and API-token Basic auth, and labels API tokens deprecated."),
            ev("credential_access", "API requests require a verified Zendesk user; OAuth tokens address one instance and public integrations must use global OAuth tokens.", "https://developer.zendesk.com/api-reference/introduction/security-and-auth/", "Security and authentication | Zendesk Developer Docs", "official_auth_docs", "The page says a verified user is required, instance OAuth is tied to the client instance, and public multi-customer apps must use global OAuth."),
            ev("self_serve", "Zendesk offers trial signup and paid Support/Suite plans, but the opened pricing page does not establish which plan confers API access.", "https://www.zendesk.com/pricing/", "Zendesk Pricing Plans | Starting from $19/month", "official_pricing", "Opened page lists Try for free, Support Team and Suite plans; no API entitlement-to-plan mapping was established."),
            ev("api", "Zendesk's Support API is the Ticketing API for tickets, users, organizations, custom objects, and ticket workflows.", "https://developer.zendesk.com/api-reference/ticketing/introduction/", "Ticketing | Zendesk Developer Docs", "official_api_docs", "Official Ticketing introduction names tickets, users, organizations, custom objects, and ticket workflow management."),
            ev("mcp", "The opened official Zendesk API references describe REST/auth but do not establish an official MCP server; status is kept UNKNOWN.", "https://developer.zendesk.com/api-reference/ticketing/introduction/", "Ticketing | Zendesk Developer Docs", "official_docs", "This page is an API reference and does not itself make an MCP ownership or availability claim.", "context"),
            ev("buildability", "Zendesk REST is buildable for core support actions, subject to verified-user auth and global OAuth for public distribution.", "https://developer.zendesk.com/api-reference/introduction/security-and-auth/", "Security and authentication | Zendesk Developer Docs", "official_auth_docs", "Official auth docs distinguish instance OAuth from the required global OAuth approach for apps distributed to multiple customers."),
        ],
        "MEDIUM",
        ["No Zendesk instance, verified account, OAuth client, API call, or plan entitlement was tested.", "The pricing page does not map API access to a trial or tier.", "MCP status remains UNKNOWN after a bounded official-domain search; no broad repository/marketplace audit was completed."],
        "API tokens are documented but deprecated; do not treat public API documentation or a free trial as proof of unrestricted production credentials.",
    ),
    rec(
        12, "Intercom", "http://intercom.com/",
        "Customer-service platform for support conversations, messaging, shared inboxes, tickets, and customer data, with Fin AI features.",
        "CONFIRMED", ["OAuth 2.0", "Bearer/token"],
        "SELF_SERVE_WITH_RESTRICTIONS",
        "Intercom offers self-serve trial signup, but the official Conversations API reference says the API is available only to apps with a trial or active subscription. Plan, usage, and API scope conditions still apply; the pricing page does not state trial duration in the opened text.",
        "RESTRICTED",
        "For a private integration, create an app in the target workspace and retrieve its access token in Developer Hub. For an app accessing other workspaces, implement OAuth; Intercom says not to request customers' private access tokens.",
        "Conversations API requires a trial or active subscription. OAuth is required for public/multi-workspace apps, and tokens/scopes inherit workspace permissions. Official MCP supports US and EU hosted workspaces, not AU.",
        "YES", ["REST"], "MODERATE",
        "Directly reviewed REST documentation covers conversation creation, listing, replying, and management; the first-party MCP guide additionally documents access to conversations, contacts, companies, articles, and other API-backed tools. The REST endpoint inventory was not exhaustively sampled in this batch, so breadth is conservatively MODERATE.",
        "AVAILABLE",
        "Intercom hosts official remote MCP endpoints: https://mcp.intercom.com/mcp for US and https://mcp.eu.intercom.com/mcp for EU workspaces. Official docs list 14 tools; user permissions and requested OAuth/API permissions govern access. AU-hosted workspaces are not yet supported.",
        "Opened first-party Intercom/Fin MCP guide, API authentication docs, and the Conversations API reference. MCP availability and regional restriction are explicit; no MCP session was connected or tested.",
        "BUILDABLE_WITH_CONSTRAINTS",
        "A workspace trial or active subscription is needed for the Conversations API; public apps use OAuth, and MCP is unavailable for AU-hosted workspaces.",
        "Documented REST operations and an official MCP provide useful agent access, but subscription, OAuth consent/scope, and workspace-region requirements affect rollout.",
        [
            ev("description", "Intercom presents its product as an integrated customer-service platform with support, messaging, and Fin AI Agent.", "https://www.intercom.com/pricing", "Intercom Pricing | Plans for every team size", "official_pricing", "Opened page describes customer service plans, shared inbox/ticketing, messaging, help center, and Fin AI Agent."),
            ev("auth", "Private Intercom apps use workspace access tokens and public apps use OAuth 2.0; API requests send the token as a Bearer credential.", "https://developers.intercom.com/docs/build-an-integration/learn-more/authentication", "Authentication | Intercom and Fin Developer Platform", "official_auth_docs", "Official guide distinguishes private Access Tokens from public-app OAuth and shows Authorization: Bearer."),
            ev("credential_access", "A private app access token is generated after creating an app in the workspace; apps requesting access to other workspaces must use OAuth.", "https://developers.intercom.com/docs/build-an-integration/learn-more/authentication", "Authentication | Intercom and Fin Developer Platform", "official_auth_docs", "Guide gives Developer Hub path for a workspace token, requires OAuth for other people's data, and prohibits requesting users' access tokens."),
            ev("self_serve", "Intercom pricing offers free-trial signup; the Conversations API is documented as available only to apps with a trial or active subscription.", "https://developers.intercom.com/docs/references/1.1/rest-api/conversations/conversations", "Conversations | Intercom and Fin Developer Platform", "official_api_docs", "Official Conversations reference states that this API is only available to apps with a trial or active subscription."),
            ev("api", "Intercom documents a REST Conversations API with read/list, start, reply, close/reopen, assignment, and other operations.", "https://developers.intercom.com/docs/references/1.1/rest-api/conversations/conversations", "Conversations | Intercom and Fin Developer Platform", "official_api_docs", "Opened reference lists conversation operations and explicitly documents the trial/subscription gate."),
            ev("mcp", "Intercom's first-party remote MCP server provides 14 tools and is supported for US and EU, but not AU, hosted workspaces.", "https://developers.intercom.com/docs/guides/mcp", "Model Context Protocol (MCP) | Intercom and Fin Developer Platform", "official_docs", "Official guide lists US/EU endpoints, states AU is not yet supported, and documents 14 API-backed tools."),
            ev("buildability", "Intercom supports REST and first-party MCP, subject to subscription, workspace region, OAuth scopes, and user permissions.", "https://developers.intercom.com/docs/guides/mcp", "Model Context Protocol (MCP) | Intercom and Fin Developer Platform", "official_docs", "The MCP guide describes regional endpoints and permission checks; API authentication docs distinguish private tokens from public OAuth."),
        ],
        "HIGH",
        ["No Intercom workspace, trial, app, API call, or MCP session was created.", "Only the Conversations API family was directly inspected as an individual REST reference; overall API breadth is therefore conservative.", "Fin outcome and seat pricing are usage-dependent; no price estimate is used as an API credential claim."],
        "Use OAuth for public integrations; do not request a customer's private workspace access token. MCP region support is an explicit constraint, not a negative API finding.",
    ),
    rec(
        13, "Freshdesk", "http://freshdesk.com/",
        "Customer-support helpdesk for ticketing, shared inboxes, customer portals, knowledge bases, and agent workflows.",
        "CONFIRMED", ["API key", "Basic"],
        "PAID_PLAN_REQUIRED",
        "The current Freshdesk support plan matrix marks API-key functionality unavailable on Free and available on Growth, Pro, and Enterprise. Pricing offers self-serve trial entry for paid plans, but trial entitlements were not tested. Freshdesk MCP is generally available on Growth, Pro, and Enterprise with plan-based action allowances and optional action packs.",
        "RESTRICTED",
        "A verified agent retrieves the personal API key from Profile Settings after CAPTCHA verification. API calls use the key with HTTP Basic authentication; the agent's role permissions govern permitted actions.",
        "The current plan table excludes Free from API-key/API functionality. MCP supports Growth, Pro, and Enterprise only, with per-minute limits and annual included actions; the published Freshdesk pricing page lists additional MCP action packs.",
        "YES", ["REST"], "BROAD",
        "The official REST v2 reference documents ticket CRUD, conversations/replies, contacts, companies, agents, ticket fields/forms, and other helpdesk resources. API quotas are plan-based. The separate official MCP surface is an API-key-authenticated agent interface, not a separate REST API type.",
        "AVAILABLE",
        "Freshworks' first-party Freshdesk MCP endpoint is https://<subdomain>.freshdesk.com/mcp. Freshdesk support says GA began September 10, 2026, supports MCP-compatible clients, and currently authenticates with an API key only. Growth, Pro, and Enterprise have annual included action allowances and per-minute limits.",
        "Opened Freshdesk API reference, first-party MCP support article, current API-key help article, and Freshdesk pricing page. MCP plan matrix and API-key plan matrix are directly documented; no MCP connection was tested.",
        "BUILDABLE_WITH_CONSTRAINTS",
        "Free excludes API access; verified API-key/role access, paid-tier rate limits, and the Freshdesk MCP action allowance/add-on structure constrain deployment.",
        "Freshdesk offers broad REST resources and a first-party MCP integration, but a supported paid plan, verified agent credentials, and usage quotas are material requirements.",
        [
            ev("description", "Freshdesk pricing describes a helpdesk with ticketing, shared inbox, customer portal, knowledge base, and support workflows.", "https://www.freshworks.com/freshdesk/pricing/", "Freshdesk Customer Support Software Pricing & Plans | Freshworks", "official_pricing", "Opened pricing page lists ticketing, shared inbox, customer portal, knowledge base, roles, and plan tiers."),
            ev("auth", "Freshdesk REST API v2 accepts the user's API key through HTTP Basic authentication, with a dummy password.", "https://developer.freshdesk.com/api/", "Freshdesk", "official_auth_docs", "Official API authentication section shows curl with API-key username and dummy password."),
            ev("credential_access", "An agent retrieves the API key in Profile Settings after verification/CAPTCHA; API activity follows that agent's role permissions.", "https://support.freshdesk.com/support/solutions/articles/215517-how-to-find-your-api-key", "How To Find Your API Key : Freshdesk Support", "official_support", "Current support article gives the profile path, CAPTCHA/verified-agent requirement, and role-based activity note."),
            ev("self_serve", "Freshdesk's current support matrix marks API key functionality unavailable on Free and available on Growth, Pro, and Enterprise; the pricing page offers trial signup for paid plans.", "https://support.freshdesk.com/support/solutions/articles/225435-where-can-i-find-my-api-key-", "Where can I find my API key? : Freshdesk Support", "official_support", "Opened current-plan table marks Free with a cross and Growth/Pro/Enterprise with checkmarks for API key availability; historical plan rows are separately labeled."),
            ev("api", "The official Freshdesk REST v2 API includes tickets, ticket conversations, contacts, agents, ticket fields/forms, and other support resources.", "https://developer.freshdesk.com/api/", "Freshdesk", "official_api_docs", "Opened API reference index enumerates ticket CRUD/replies, conversations, ticket forms/fields, account, and related resource groups."),
            ev("mcp", "Freshdesk offers a first-party MCP endpoint with API-key-only authentication; GA began September 10, 2026, and Growth/Pro/Enterprise have plan-specific action limits/allowances.", "https://support.freshdesk.com/support/solutions/articles/50000012670-model-context-protocol-mcp-integration-in-freshdesk", "Model Context Protocol (MCP) integration in Freshdesk : Freshdesk Support", "official_support", "Official article gives the subdomain /mcp URL, API-key-only note, GA date, supported plans, action/minute caps, and annual included actions."),
            ev("buildability", "Freshdesk can be integrated through REST or first-party MCP, with plan, verified-user, role, rate-limit, and MCP-action constraints.", "https://www.freshworks.com/freshdesk/pricing/", "Freshdesk Customer Support Software Pricing & Plans | Freshworks", "official_pricing", "Pricing page lists Growth/Pro/Enterprise and MCP action packs; the support articles document role and plan constraints."),
        ],
        "HIGH",
        ["No Freshdesk account, verified agent, API key, API request, or MCP connection was used.", "The 2024 support article retains legacy plan labels; its current-plan section and the 2026 API-key article were used for current plan interpretation.", "Freshdesk pricing and MCP action-pack amounts can change; no production cost estimate is inferred."],
        "Freshdesk's current first-party MCP article is newer than community/local Freshdesk MCP projects; only Freshworks-owned MCP is counted as AVAILABLE.",
    ),
    rec(
        14, "Front", "http://front.com/",
        "Customer-operations platform with a shared inbox and APIs for syncing, retrieving, creating, updating, and deleting conversations and related resources.",
        "CONFIRMED", ["API key", "Bearer/token", "OAuth 2.0"],
        "SELF_SERVE_WITH_RESTRICTIONS",
        "Front provides a free developer environment for API work, limited to three teammates. API tokens are a quick path for an internal/single-customer integration; public integrations must use OAuth unless Front grants an exception. Public partnership/listing is a separate process.",
        "SELF_SERVE",
        "Create a free Front developer account and generate an API token for internal or single-customer testing; register a developer app/OAuth feature for a public integration. The MCP server also requires a confidential OAuth connection carrying client ID and secret.",
        "Public distribution requires OAuth unless Front grants an exception. Front MCP is open beta, does not support Dynamic Client Registration, and inherits the authorizing teammate's permissions and selected scopes.",
        "YES", ["REST", "Webhooks"], "BROAD",
        "The Core API supports CRUD across contacts, comments, tags, conversations and other entities; webhooks support real-time events. Front also documents separate Channel API, Plugin SDK, and connector surfaces, which are not counted as Core REST endpoints here.",
        "AVAILABLE",
        "Front operates an official open-beta remote MCP server at https://mcp.frontapp.com/mcp. It uses OAuth 2.1/PKCE-compatible confidential client credentials, per-user authorization, and read/write/send scopes; clients requiring DCR cannot connect.",
        "Opened Front's first-party Welcome, Authentication, and MCP Server pages. The dev-account and API framework are explicit; open-beta status, endpoint, auth, and DCR limitation are explicit.",
        "BUILDABLE_WITH_CONSTRAINTS",
        "Public integrations require OAuth; Front MCP is open beta and requires a client ID/secret (no DCR). Tools inherit the user's role and scopes.",
        "A free developer environment and broad REST/webhook surfaces enable development, but public distribution, beta MCP compatibility, OAuth setup, and user-scoped authorization are material constraints.",
        [
            ev("description", "Front describes its platform APIs as covering shared-inbox data and operations including contacts, comments, tags, syncing, and conversation actions.", "https://dev.frontapp.com/docs/welcome", "Welcome", "official_docs", "Opened overview lists Core API CRUD, MCP, Connectors, Plugin SDK, Channel API, and Chat Widget."),
            ev("auth", "Front Core API accepts Bearer tokens obtained through settings API tokens or OAuth; public integrations must use OAuth absent an exception.", "https://dev.frontapp.com/docs/authentication", "Authentication", "official_auth_docs", "Official guide documents Bearer token requests, internal token use, OAuth, and the public-integration OAuth rule."),
            ev("credential_access", "Front offers a free developer environment limited to three teammates and documents API-token creation for internal work and app OAuth credentials for public work.", "https://dev.frontapp.com/docs/welcome", "Welcome", "official_docs", "Official welcome page provides a free developer signup path, a three-teammate limit, and links to create/manage apps."),
            ev("self_serve", "Front public integrations use the app framework and OAuth; a developer account is self-serve and free for development.", "https://dev.frontapp.com/docs/partnering-with-front", "Partnering With Front", "official_docs", "First-party partnership page says developers can sign up for a free development account and distinguish public partnership from a private/single-client integration."),
            ev("api", "Front's Core API supports CRUD across Front entities and webhooks for real-time changes.", "https://dev.frontapp.com/docs/welcome", "Welcome", "official_api_docs", "Opened API overview names contacts, comments, tags, and Core API read/create/update/delete plus webhooks."),
            ev("mcp", "Front hosts an open-beta MCP server at mcp.frontapp.com/mcp with OAuth 2.1/PKCE-compatible confidential credentials, per-user scopes, and no DCR support.", "https://dev.frontapp.com/docs/mcp-server", "MCP Server", "official_docs", "Official MCP guide states endpoint, open beta, transport, client-secret requirement, per-user identity, scopes, and DCR incompatibility."),
            ev("buildability", "Front APIs are buildable with an internal token or public OAuth app, while public distribution and MCP client compatibility add constraints.", "https://dev.frontapp.com/docs/authentication", "Authentication", "official_auth_docs", "The official guide makes OAuth mandatory for public integrations unless an exception is granted; MCP needs a confidential OAuth connection."),
        ],
        "HIGH",
        ["No Front account, OAuth app, API token, API call, or MCP session was created.", "MCP is explicitly open beta; tool behavior and client compatibility may change.", "Front's current product-specific subscription/API entitlement was not tested; the documented free development environment is not equated with production access."],
        "Do not confuse the free developer sandbox/environment with an entitled production customer account. MCP permission scope is per authorizing teammate.",
    ),
    rec(
        15, "Pylon", "http://usepylon.com/",
        "B2B customer-support platform with programmatic access to customer accounts, issues, contacts, messages, and related support data.",
        "CONFIRMED", ["API key", "Bearer/token", "OAuth 2.0"],
        "UNKNOWN",
        "Official API and support docs establish API/MCP credentials inside an existing Pylon workspace, but the reviewed pricing URL repeatedly redirected to a demo-booking page. A public signup/trial path and the precise plan entitlement for API/MCP therefore remain unresolved.",
        "RESTRICTED",
        "For REST API access, an Admin creates a named token in Settings > API Tokens; the token is shown once and sent as Authorization: Bearer. For MCP, a Member or Admin seat authorizes through browser OAuth; Viewer and Integration seats cannot connect.",
        "API-token creation is admin-only. MCP is OAuth-only (no API key or machine-to-machine authentication), requires a Member/Admin seat, and inherits the user's Pylon permissions. The specific plan gate could not be verified from an opened pricing matrix.",
        "YES", ["REST", "Webhooks"], "BROAD",
        "Pylon's first-party API/Webhooks material says integrations can read and act on data across accounts, contacts, issues, messages, tasks/projects, knowledge base, custom fields/objects, tags, macros, surveys, teams, and users; webhooks push events to customer endpoints.",
        "AVAILABLE",
        "Pylon's official MCP endpoint is https://mcp.usepylon.com/. It uses browser OAuth only, acts on behalf of the logged-in user, and supports issue/account/contact access; notebook block content is not currently retrievable through MCP.",
        "Opened Pylon's API index/authentication docs, API & Webhooks page, and Pylon support articles on API tokens and MCP. Pricing URL attempts redirected to the general demo form, so account/plan access was not resolved.",
        "BUILDABLE_WITH_CONSTRAINTS",
        "REST tokens require a Pylon Admin; MCP requires a Member/Admin OAuth login and cannot use machine credentials. Account/trial/plan entitlement remains unknown.",
        "A broad documented REST/webhook surface and official hosted MCP make the connector technically feasible, but credentials are role-gated, MCP is OAuth-only, and pricing/account access was not established.",
        [
            ev("description", "Pylon describes its API as programmatic access to Pylon data and its MCP as a way for AI tools to access support issues, accounts, and contacts.", "https://docs.usepylon.com/pylon-docs/developer/api", "API | Pylon", "official_api_docs", "Official API overview names customer and issue data and directs users to the complete endpoint reference."),
            ev("auth", "Pylon REST requests use a Bearer API token; Pylon MCP uses a separate browser OAuth flow.", "https://docs.usepylon.com/pylon-docs/developer/api/authentication", "Authentication | Pylon", "official_auth_docs", "Official API docs specify Authorization: Bearer; Pylon's MCP setup article explicitly requires OAuth and says API-key auth is unavailable for MCP."),
            ev("credential_access", "Only Admin users can create API tokens from Settings > API Tokens; a token is shown once and can be role-limited.", "https://support.usepylon.com/articles/4735104435-how-do-i-create-an-api-token", "How do I create a Pylon API token? | Pylon Knowledge Base", "official_support", "Opened support article documents the settings path, one-time token display, and admin/permission requirement."),
            ev("self_serve", "The attempted official Pylon pricing URLs redirected to a demo-booking page rather than an inspectable plan matrix, so self-serve/trial and plan entitlement remain unknown.", "https://www.usepylon.com/schedule-demo", "Book a Demo | Pylon", "official_product", "Direct fetch returned a required-field 30-minute demo form; it did not expose pricing or API/MCP plan availability."),
            ev("api", "Pylon documents REST API and webhooks for reading and acting on multiple support object groups, including customers/accounts, issues, messages, tasks/projects, knowledge base, and custom objects.", "https://www.usepylon.com/integrations/api-webhooks", "API & Webhooks Integration | Pylon", "official_api_docs", "Opened first-party integration page describes API reads/writes and event webhooks across the named resource areas."),
            ev("mcp", "Pylon hosts an OAuth-only MCP server at mcp.usepylon.com; it requires a Member/Admin seat and inherits the authorizing user's permissions.", "https://support.usepylon.com/articles/2407390554-connecting-to-the-pylon-mcp-server", "How do I connect to the Pylon MCP Server? | Pylon Knowledge Base", "official_support", "Official support article gives endpoint, OAuth-only rule, no machine/API-key auth, user-scoped access, and Member/Admin seat requirement."),
            ev("buildability", "Pylon can be integrated through REST/webhooks or official MCP, but API token creation is Admin-only and MCP requires interactive OAuth and an eligible seat.", "https://support.usepylon.com/articles/2407390554-connecting-to-the-pylon-mcp-server", "How do I connect to the Pylon MCP Server? | Pylon Knowledge Base", "official_support", "Official setup guide distinguishes OAuth MCP from REST Bearer token authentication and documents eligible seat types."),
        ],
        "MEDIUM",
        ["No Pylon workspace, API token, trial, MCP session, or account signup was used.", "Pricing/trial/API-plan status is unresolved: three official pricing URL attempts resolved to a demo page; search snippets were treated only as discovery and not as evidence.", "Pylon MCP does not currently expose notebook block content; OAuth sessions expire and may require reconnection."],
        "Do not transfer the REST API's admin-created Bearer token model to MCP; MCP is OAuth-only. The pricing redirect is preserved as a research limitation rather than filled from search snippets.",
    ),
    rec(
        16, "LiveAgent", "http://liveagent.com/",
        "Helpdesk and customer-support suite with ticketing, live chat, knowledge base, automation, and call-center features.",
        "CONFIRMED", ["API key", "Bearer/token", "OAuth 2.0"],
        "SELF_SERVE_WITH_RESTRICTIONS",
        "LiveAgent advertises a 30-day no-credit-card trial and paid per-agent tiers. Its hosted MCP tools count against the account's AI-credit budget; the current API v3 reference is available from within a customer account, so the trial does not by itself prove every API operation or entitlement.",
        "RESTRICTED",
        "For MCP, an agent generates an access token from Profile > MCP Integration or completes OAuth 2.1 authorization-code/PKCE. The legacy public REST API reference uses an API key; the API v3 reference is exposed inside the LiveAgent account.",
        "MCP actions run under the connecting agent's role permissions and consume the account's AI-credit budget. The public API v1 material is older; full API v3 documentation/testing requires an account session.",
        "YES", ["REST"], "BROAD",
        "The opened public REST API v1 reference documents conversations/messages, customers, companies, knowledge-base articles, reports, tags, files, and agents. LiveAgent also says API v3 documentation and interactive testing are available inside the account; v3 endpoint details were not inspected here.",
        "AVAILABLE",
        "LiveAgent offers a tenant-specific hosted MCP server at https://<your-liveagent-domain>/api/mcp with Streamable HTTP and either generated Bearer tokens or OAuth 2.1 authorization-code + PKCE. Tools execute as the agent and are limited by their role; MCP calls count against AI credits.",
        "Opened LiveAgent's first-party MCP article, public API v1 reference, and pricing page. The MCP guide is current; the REST v1 reference is older and current API v3 docs require account access.",
        "BUILDABLE_WITH_CONSTRAINTS",
        "The server URL is tenant-specific, agent role permissions apply, MCP uses AI credits, and the current v3 API reference is account-gated.",
        "A broad REST surface and first-party MCP are documented, but tenant-specific setup, role-scoped actions, credit consumption, and limited public visibility into current API v3 details affect implementation.",
        [
            ev("description", "LiveAgent pricing describes a multichannel support product with ticketing, live chat, knowledge base, automation, and call-center capabilities.", "https://www.liveagent.com/pricing/", "Pricing | LiveAgent - Help Desk Software & Live Chat", "official_pricing", "Opened pricing page lists ticketing, chat, knowledge base, customer portal, automation, and call-center features."),
            ev("auth", "LiveAgent's public REST v1 reference accepts an API key parameter; the separate MCP server supports generated Bearer access tokens or OAuth 2.1 with PKCE.", "https://support.liveagent.com/647358-MCP-Integration-for-Agents", "MCP Integration for Agents", "official_support", "MCP article documents the hosted URL, Bearer token and OAuth 2.1 flows; the public API reference shows an API key parameter."),
            ev("credential_access", "An agent can generate an MCP token in Profile > MCP Integration or authorize an OAuth client; actions are attributed to the agent identity.", "https://support.liveagent.com/647358-MCP-Integration-for-Agents", "MCP Integration for Agents", "official_support", "The setup page describes profile token creation, OAuth approval, revocation, and actor attribution."),
            ev("self_serve", "LiveAgent offers a 30-day free trial without a credit card and lists paid Small/Medium/Large/Enterprise tiers.", "https://www.liveagent.com/pricing/", "Pricing | LiveAgent - Help Desk Software & Live Chat", "official_pricing", "Opened plan comparison states 30 days free trial, no credit card required, and per-agent paid tiers."),
            ev("api", "LiveAgent's public REST v1 reference covers conversations/messages, customers, companies, knowledge base, reports, tags, files, and agents.", "https://support.liveagent.com/840770-Complete-API-reference", "Complete API reference", "official_api_docs", "Opened API reference table of contents lists the named resource groups and read/write operations."),
            ev("mcp", "LiveAgent's first-party MCP endpoint is tenant-specific and uses Streamable HTTP with Bearer token or OAuth 2.1/PKCE; tools run under agent permissions and consume AI credits.", "https://support.liveagent.com/647358-MCP-Integration-for-Agents", "MCP Integration for Agents", "official_support", "The support article documents endpoint/auth modes, full tool access subject to role, audit attribution, and AI-credit budget impact."),
            ev("buildability", "LiveAgent supports REST and first-party MCP but deployment depends on an existing tenant, agent permissions, AI-credit budget, and tenant-specific endpoint.", "https://support.liveagent.com/647358-MCP-Integration-for-Agents", "MCP Integration for Agents", "official_support", "Official guide specifies user identity, role-based permissions, per-tenant URL, and credit consumption."),
        ],
        "MEDIUM",
        ["No LiveAgent account, API key, MCP token, OAuth client, or API call was used.", "The public API v1 page is legacy; the API v3 reference is exposed within an account and was not inspected.", "No specific API entitlement by plan was established; trial/pricing statements refer to the product page, not guaranteed API v3 feature parity."],
        "Keep REST API v1, in-account API v3, and the MCP token/OAuth flow distinct; do not imply MCP uses the legacy API-key query parameter.",
    ),
    rec(
        17, "Plain", "http://plain.com/",
        "Support platform for customer-service teams with thread, customer, tenant, and workflow data exposed through GraphQL and agent tooling.",
        "CONFIRMED", ["API key", "Bearer/token", "OAuth 2.0"],
        "SELF_SERVE_WITH_RESTRICTIONS",
        "Plain advertises a seven-day free trial with no credit card and self-serve Foundation pricing. API credentials require a workspace machine user and explicitly selected permissions; the opened pricing table does not reliably map every API/MCP capability to each tier.",
        "RESTRICTED",
        "In a Plain workspace, create a Machine User under Settings > Machine Users, add a fine-grained API key, and copy it once. For hosted MCP, connect by OAuth; the MCP inherits the user's permissions and requires openid and offline_access scopes.",
        "Machine-user key permissions are explicit and granular. The MCP is user-scoped and write actions may require client confirmation; API feature availability by plan was not fully mapped in the pricing extraction.",
        "YES", ["GraphQL"], "BROAD",
        "Plain's GraphQL API is the same API used by the product and its documentation says it has no UI/API capability gap. The docs provide customer/thread operations and a schema/typed SDK; breadth is judged broad for the documented support data model, not by endpoint count.",
        "AVAILABLE",
        "Plain operates https://mcp.plain.com/mcp with OAuth. The official guide lists 30 read/write tools spanning threads, customers, tenants, and support actions; OAuth inherits the user's access and requires openid offline_access scopes.",
        "Opened Plain GraphQL introduction/authentication, official MCP setup, and pricing pages. An initial noncanonical /docs/api URL returned 404; the current GraphQL docs URL was found and opened. No live workspace/token/MCP session was tested.",
        "BUILDABLE_WITH_CONSTRAINTS",
        "A workspace and machine-user permission setup are required for API keys; hosted MCP requires interactive OAuth and client support for token refresh/scopes. Plan mapping is incomplete.",
        "Plain offers a broad documented GraphQL API and first-party MCP, but credentials are scoped, OAuth is user-bound, and ongoing plan/API entitlement details need confirmation for a production deployment.",
        [
            ev("description", "Plain's product documentation describes a support platform whose GraphQL API is used by the product itself and provides access to customer/workflow data.", "https://www.plain.com/docs/graphql/introduction", "Introduction - Plain Docs", "official_api_docs", "Official API introduction says Plain itself is built on the same GraphQL API and links support-agent operations."),
            ev("auth", "Plain's GraphQL API uses Bearer authentication with a machine-user API key; the hosted MCP uses OAuth.", "https://www.plain.com/docs/graphql/authentication", "Authentication - Plain Docs", "official_auth_docs", "The API guide documents machine users, fine-grained API keys, and Authorization: Bearer; the separate MCP guide documents OAuth."),
            ev("credential_access", "A workspace user creates a Machine User and a permission-scoped API key in Settings; the key is shown once.", "https://www.plain.com/docs/graphql/authentication", "Authentication - Plain Docs", "official_auth_docs", "The official guide lists Settings > Machine Users, Add API Key, explicit permission selection, and one-time copy."),
            ev("self_serve", "Plain offers a seven-day free trial without a credit card and a self-serve Foundation plan; API feature placement is not fully mapped in the extracted pricing table.", "https://www.plain.com/pricing", "Plain Pricing — Plans from $35/seat/month | 7-Day Free Trial", "official_pricing", "Opened pricing page says start today/no credit card, shows Foundation/Horizon/Frontier, and a seven-day trial; extension rows do not reliably map every feature to plan."),
            ev("api", "Plain's GraphQL API is used by its own product and the docs describe a schema, customer operations, and a typed SDK.", "https://www.plain.com/docs/graphql/introduction", "Introduction - Plain Docs", "official_api_docs", "Official page gives GraphQL endpoint, schema URL, customer query example, and links API schema/SDK documentation."),
            ev("mcp", "Plain hosts an official MCP server at mcp.plain.com/mcp with OAuth, user permission inheritance, and 30 tools including reads and writes.", "https://www.plain.com/docs/integrations/mcp-server", "MCP server - Plain Docs", "official_docs", "Opened guide names endpoint, OAuth, required scopes, inherited permissions, and the tool table across threads/customers/tenants."),
            ev("buildability", "Plain is technically buildable via GraphQL or MCP, but scoped machine-user keys, OAuth client support, and uncertain plan mapping constrain deployment.", "https://www.plain.com/docs/integrations/mcp-server", "MCP server - Plain Docs", "official_docs", "The guide documents user-scoped OAuth, required scopes, refresh considerations, and client behavior; API docs document scoped machine-user keys."),
        ],
        "HIGH",
        ["No Plain account, machine user, API key, trial, API call, or MCP session was created.", "An initial /docs/api URL returned 404; the authoritative current GraphQL docs were found and opened.", "The pricing feature matrix extracted API rows without reliable plan checkmarks, so no all-plan API entitlement is asserted."],
        "API-key identity (machine user) and MCP identity (OAuth user) are separate credential models.",
    ),
    rec(
        18, "Help Scout", "http://helpscout.com/",
        "Customer-support platform with a shared inbox, conversations, customer records, knowledge bases, workflows, and reporting.",
        "CONFIRMED", ["OAuth 2.0", "Bearer/token", "API key"],
        "PAID_PLAN_REQUIRED",
        "Help Scout's API and MCP access is included on Standard, Plus, and Pro plans; the official pricing page also lists a separate Free plan. The MCP guide says new connections are read-only; Reports require Plus/Pro and Docs knowledge-base tools need a separate Docs API key.",
        "RESTRICTED",
        "Create an OAuth2 application from Your Profile > My Apps and use Authorization Code for a user-facing integration or Client Credentials for an internal integration. Credentials must be associated with an active, invited Help Scout user. MCP connects the user's account through OAuth; Docs API tools require a separate Docs API key.",
        "The API/MCP entitlement is paid-plan gated to Standard/Plus/Pro. An active invited user is required. Reports require Plus/Pro; Docs requires its own API key; new MCP connections are read-only.",
        "YES", ["REST"], "BROAD",
        "Help Scout documents Inbox API v2 and Docs API surfaces. The Inbox API is HTTPS/JSON and covers conversations, customers, users/inboxes and reports; the official MCP guide lists those resources plus optional Docs content. No endpoint count is inferred.",
        "AVAILABLE",
        "Help Scout's official remote MCP endpoint is https://mcp.helpscout.net/mcp. New connections are read-only and access follows the connecting user's Help Scout permissions; Standard/Plus/Pro include API access, reports need Plus/Pro, and Docs search needs a separate Docs API key.",
        "Opened Help Scout API overview/authentication, current pricing, and first-party MCP support guide. An initial official-blog URL returned 404; the current official support setup guide directly established MCP availability and requirements.",
        "BUILDABLE_WITH_CONSTRAINTS",
        "Paid Standard/Plus/Pro entitlement and an active invited user are required; MCP is read-only, reports need Plus/Pro, and Docs has a separate API key.",
        "A documented REST API and official MCP support core retrieval use cases, but paid-plan/API access, account permissions, read-only MCP, and separate Docs credentials constrain actions.",
        [
            ev("description", "Help Scout pricing lists support features including inboxes, live chat, SMS, workflows, and knowledge bases.", "https://www.helpscout.com/pricing/", "Help Scout Pricing: Affordable Customer Support Software", "official_pricing", "Opened page lists shared inbox-related features, channels, workflows, Docs sites, and Free/Standard/Plus/Pro plans."),
            ev("auth", "Help Scout Mailbox API uses OAuth 2.0 Authorization Code or Client Credentials and sends access tokens as Bearer credentials.", "https://developer.helpscout.com/mailbox-api/overview/authentication/", "Authentication | Help Scout Developers", "official_auth_docs", "Official guide documents both OAuth2 flows, Authorization: Bearer, and token refresh/expiry behavior."),
            ev("credential_access", "An OAuth app is created in Your Profile > My Apps; API credentials must be associated with an active, invited account user.", "https://developer.helpscout.com/mailbox-api/overview/authentication/", "Authentication | Help Scout Developers", "official_auth_docs", "The guide gives the My Apps path and states an active, invited user is required for all credentials."),
            ev("self_serve", "Help Scout API access is included on Standard, Plus, and Pro; the official product page separately lists a Free plan.", "https://docs.helpscout.com/article/1779-connect-your-ai-agent-with-help-scout-to-search-conversations-and-pull-reports", "Connect your AI Agent to Help Scout via MCP - Help Scout Support", "official_support", "Official setup article says API access is included in Standard, Plus, and Pro; the pricing page lists a separate Free tier."),
            ev("api", "Help Scout provides an HTTPS/JSON Inbox API v2 with OAuth and endpoints for support data; the MCP guide identifies conversations, customers, inboxes, users, reports, and optional Docs.", "https://developer.helpscout.com/mailbox-api/", "Inbox API 2.0 | Help Scout Developers", "official_api_docs", "Opened API overview specifies HTTPS/JSON, OAuth2, and v2 endpoint; official MCP guide lists resource groups exposed through the product API."),
            ev("mcp", "Help Scout hosts an official MCP server at mcp.helpscout.net/mcp; new connections are read-only and follow the user's existing Help Scout permissions.", "https://docs.helpscout.com/article/1779-connect-your-ai-agent-with-help-scout-to-search-conversations-and-pull-reports", "Connect your AI Agent to Help Scout via MCP - Help Scout Support", "official_support", "Support guide documents endpoint, paid-plan access, read-only operation, per-user credentials, and separate Docs API key."),
            ev("buildability", "Help Scout supports API/MCP retrieval on Standard/Plus/Pro, but paid plans, read-only MCP, report tier, and Docs API key constraints shape deployment.", "https://docs.helpscout.com/article/1779-connect-your-ai-agent-with-help-scout-to-search-conversations-and-pull-reports", "Connect your AI Agent to Help Scout via MCP - Help Scout Support", "official_support", "Official guide states plan/access tiers, read-only behavior, report requirement, and Docs-key requirement."),
        ],
        "HIGH",
        ["No Help Scout account, OAuth app, API call, Docs API key, or MCP connection was used.", "A first-party marketing-blog URL returned 404; the current official support setup guide was directly opened and used.", "New MCP connections are read-only; a small number of former beta connections retained write tools, which is not treated as the general case."],
        "Do not conflate Help Scout Inbox OAuth credentials with the separate Docs API key. Treat the July 2026 GA announcement as confirmed by current first-party setup documentation, not by third-party MCP directories.",
    ),
    rec(
        19, "Gorgias", "http://gorgias.com/",
        "Customer-support helpdesk for ecommerce teams, with ticketing and an AI Agent available alongside the support inbox.",
        "CONFIRMED", ["API key", "Basic", "OAuth 2.0"],
        "SELF_SERVE_WITH_RESTRICTIONS",
        "Gorgias offers self-serve trial signup and paid helpdesk plans. Its API credentials are available on Helpdesk plans to owners/admins; the official first-party MCP is included at no extra cost for paid plan customers and remains open beta in the reviewed announcement.",
        "RESTRICTED",
        "For private/internal use, an account owner or admin creates a per-user API key in Settings > Account > REST API; requests use HTTP Basic with the account email and key. Public apps must use OAuth2 and follow Gorgias' developer-app approval/onboarding process.",
        "API-key creation is limited to owners/admins and grants full account data access. Public apps require OAuth2. First-party MCP requires a paid plan and uses OAuth; it is in open beta.",
        "YES", ["REST"], "MODERATE",
        "Gorgias has an official REST/JSON API reference and first-party help documentation says the API reads and writes helpdesk data. The API surface is relevant for core support integration; this batch did not exhaustively enumerate individual endpoint groups, so breadth is conservatively MODERATE.",
        "AVAILABLE",
        "Gorgias' first-party remote MCP endpoint is https://mcp.gorgias.com/mcp?gorgias_subdomain=YOUR-SUBDOMAIN. It uses OAuth and is in open beta for paid helpdesk customers; the company says it can search tickets/customer history, analyze support data, inspect macros/rules/tags, and draft AI Agent guidance.",
        "Opened Gorgias' official API authentication/reference, REST API credential help article, pricing page, and first-party MCP announcement/how-to. Search snippets were not used as final evidence; the directly opened company blog establishes current MCP status.",
        "BUILDABLE_WITH_CONSTRAINTS",
        "API keys require owner/admin access and grant full account data; public apps require OAuth2; the official MCP is paid-plan-only and open beta.",
        "Gorgias has documented REST credentials and a first-party MCP, but account role, broad token scope, public OAuth onboarding, paid subscription, and beta status are material constraints.",
        [
            ev("description", "Gorgias pricing describes a helpdesk plus AI Agent for customer support and ecommerce brands.", "https://www.gorgias.com/pricing", "Gorgias Pricing – Build the customer support suite that fits your needs", "official_pricing", "Opened page lists Helpdesk and AI Agent plans, ticket volumes, and support positioning."),
            ev("auth", "Gorgias private apps use an API key with HTTP Basic credentials; public apps use OAuth2, which is mandatory for public apps.", "https://developers.gorgias.com/reference/authentication", "Authentication", "official_auth_docs", "Developer docs distinguish private-app API keys from public-app OAuth2 and say OAuth2 is mandatory for public apps."),
            ev("credential_access", "Owners/admins can create per-user API keys in the helpdesk REST API settings; the key uses the account email and gives full account-data access.", "https://helpcenter.gorgias.com/en-US/rest-api-208286", "Access your Gorgias REST API credentials | Gorgias Help Center", "official_support", "Opened help article gives API settings path, owner/admin requirement, Basic credentials, and full-access warning."),
            ev("self_serve", "Gorgias pricing offers free-trial signup and paid Helpdesk plans; its official MCP article says MCP is included for all paid plans at no extra cost.", "https://www.gorgias.com/pricing", "Gorgias Pricing – Build the customer support suite that fits your needs", "official_pricing", "Opened pricing page lists paid tiers, trial signup, and per-ticket/AI usage pricing."),
            ev("api", "Gorgias publishes a REST/JSON API reference, and its help article says the API can read and write helpdesk data programmatically.", "https://developers.gorgias.com/reference/introduction", "Introduction", "official_api_docs", "Official developer overview identifies a complete REST API reference; support documentation describes programmatic read/write access."),
            ev("mcp", "Gorgias operates a first-party OAuth MCP in open beta for paid-plan customers; its documented remote URL is https://mcp.gorgias.com/mcp?gorgias_subdomain=YOUR-SUBDOMAIN.", "https://www.gorgias.com/blog/gorgias-mcp", "How to Connect Gorgias to Claude or ChatGPT (6 Workflows to Try Right Now)", "official_blog", "Gorgias' May 28, 2026 article calls it a first-party bridge, gives the mcp.gorgias.com/mcp?gorgias_subdomain=YOUR-SUBDOMAIN endpoint, OAuth setup, paid-plan requirement, and open-beta status."),
            ev("mcp", "Gorgias says the MCP is included in paid plans at no extra cost; an active subscription to an MCP-compatible AI client is separately required.", "https://www.gorgias.com/blog/gorgias-mcp", "How to Connect Gorgias to Claude or ChatGPT (6 Workflows to Try Right Now)", "official_blog", "The article says no extra cost within a Gorgias paid plan, lists Claude/ChatGPT/Cursor or compatible clients, and requires an active subscription to the selected AI tool."),

            ev("buildability", "Gorgias supports REST and first-party MCP, but admin-issued full-access API keys, OAuth onboarding, paid-plan MCP access, and beta status constrain rollout.", "https://www.gorgias.com/blog/gorgias-mcp", "How to Connect Gorgias to Claude or ChatGPT (6 Workflows to Try Right Now)", "official_blog", "Official setup article establishes paid-plan MCP and OAuth; the help article establishes admin/owner key creation and full-account-data access."),
        ],
        "MEDIUM",
        ["No Gorgias helpdesk, API key, OAuth app, API request, or MCP connection was used.", "The API is confirmed, but endpoint-family breadth was not exhaustively sampled; MODERATE is intentionally conservative.", "MCP is open beta and paid-plan-dependent; writes/analytics behavior may change. The pricing page uses ticket-volume and AI usage pricing, so no flat connector cost is inferred."],
        "Treat the official Gorgias company blog and help center as decisive for MCP/API status; third-party summaries were discovery only and were not used to establish first-party ownership.",
    ),
    rec(
        20, "Gladly", "http://gladly.com/",
        "Customer-service platform with a REST API for customer profiles, conversations, messages, tasks, answers, reports, and related support workflows.",
        "CONFIRMED", ["API key", "Basic"],
        "ADMIN_APPROVAL_REQUIRED",
        "Gladly's official company blog labels its product pricing as Custom (sales-led), while the homepage offers Get a Demo/Try it yourself; neither establishes an API-specific commercial entitlement. For an existing instance, an administrator must grant API User permission before an agent can create/use a token. Sandbox access requires purchasing/contacting a CSM or support team.", 
        "RESTRICTED",
        "A Gladly administrator grants API User permission in Settings > Users; the designated user creates an API token in Settings > API Tokens. REST requests use token-based Basic authentication with the agent email as username and API token as password.",
        "An existing customer instance and administrator-granted API User permission are required. The company blog labels Gladly product pricing Custom (sales-led), but this is not an API-specific plan matrix. Sandbox access is separately purchased/contact-mediated; the current homepage emphasizes commerce AI and does not map pricing to the developer API.",
        "YES", ["REST", "Webhooks"], "BROAD",
        "The official REST reference enumerates customers, conversations/items, agents, answers, tasks, reports, teams, communications, exports, topics, and webhooks. It also describes a sandbox endpoint, with sandbox provisioning requiring purchase/contact with a CSM/support team.",
        "UNKNOWN",
        "No first-party Gladly MCP offer was established. The official developer API index and setup guide were opened and targeted official-domain MCP searches were run, but no complete source repository/catalog audit was performed; status remains UNKNOWN.",
        "Opened Gladly's first-party REST API index and API-user setup guide, current homepage, and 2026 company pricing-comparison blog. The blog labels Gladly pricing Custom (sales-led), but does not establish API-specific entitlements. Targeted search for an official Gladly MCP server did not yield a first-party server page. The current commerce-AI positioning and developer support API documentation differ; no migration relationship was inferred.",
        "BUILDABLE_WITH_CONSTRAINTS",
        "Requires an existing Gladly tenant and administrator-granted API User permission; sandbox testing is separately purchased/contact-mediated. MCP availability is unknown.",
        "The broad REST/webhook API is usable for authorized customer instances, but role-gated token creation and tenant/sandbox access constrain a general-purpose build; no MCP capability is claimed.",
        [
            ev("description", "Gladly's official developer documentation describes a customer-service API for customer profiles, timelines, and related support data.", "https://developer.gladly.com/rest/", "Gladly API", "official_api_docs", "Official API introduction describes customer context and access to customer profiles/timelines; API groups cover support resources."),
            ev("auth", "Gladly REST API uses token-based Basic authentication with agent email as username and API token as password.", "https://help.gladly.com/developer-tutorials/docs/setup-and-testing", "Setup and Testing", "official_auth_docs", "Opened setup guide identifies token-based Basic Authentication and the user/password mapping."),
            ev("credential_access", "A Gladly administrator grants API User permission per agent; that user creates an API token in account settings.", "https://help.gladly.com/developer-tutorials/docs/setup-and-testing", "Setup and Testing", "official_support", "Official setup guide gives the Settings > Users permission steps and token creation path; a token is displayed once."),
            ev("self_serve", "Gladly's official comparison labels the product's pricing as Custom (sales-led); this product-level statement does not establish a Gladly API-specific plan entitlement.", "https://www.gladly.ai/blog/freshdesk-pricing/", "What Freshdesk actually costs in 2026 | Gladly", "official_blog", "Opened comparison table lists Gladly as Custom (sales-led); no Gladly API plan matrix is included."),
            ev("self_serve", "Gladly's current homepage offers Get a Demo and Try it yourself but does not state developer/API plan entitlements.", "https://www.gladly.ai/", "Agentic commerce platform built for top brands | Gladly", "official_product", "Opened homepage headline is 'Commerce AI for every customer moment' and links to Get a Demo/Try it yourself; no API plan matrix is shown."),
            ev("self_serve", "Gladly sandbox access requires purchasing or contacting a CSM/Support team; the developer guide does not establish a self-serve sandbox path.", "https://help.gladly.com/developer-tutorials/docs/setup-and-testing", "Setup and Testing", "official_support", "Official developer guide says sandbox environments can be purchased by contacting a CSM or Gladly Support."),
            ev("api", "Gladly's REST API covers customers, conversations/items, agents, answers, tasks, reports, communications, exports, topics, and webhooks.", "https://developer.gladly.com/rest/", "Gladly API", "official_api_docs", "Opened API table of contents lists the named REST resource groups and webhook endpoints."),
            ev("mcp", "The opened first-party Gladly API/setup documentation does not establish an MCP server; this bounded search remains UNKNOWN, not NOT_FOUND.", "https://developer.gladly.com/rest/", "Gladly API", "official_docs", "The reviewed API index describes REST, Lookup, webhooks, and app-platform tools but makes no MCP availability claim.", "context"),
            ev("buildability", "Gladly can be integrated through its REST API for an authorized tenant, but admin permission and customer-instance access are required; MCP is unknown.", "https://help.gladly.com/developer-tutorials/docs/setup-and-testing", "Setup and Testing", "official_support", "The official guide requires an API User permission granted by an administrator and describes the account-scoped token path."),
        ],
        "MEDIUM",
        ["No Gladly tenant, API token, sandbox, API call, or MCP session was available or tested.", "The current Gladly homepage and company blog position the product as commerce AI for retail/subscription brands, while developer docs describe customer-service APIs; the product/API relationship was not independently clarified.", "A 2026 Gladly company blog labels product pricing Custom (sales-led), but neither that nor the homepage establishes API-specific plan entitlement or pricing. The /pricing path redirects to the homepage.", "MCP status remains UNKNOWN after a bounded search; no tenant or sandbox API eligibility was tested."],
        "Use the developer API documentation for API scope, and preserve the current marketing/developer-documentation positioning mismatch instead of assuming an API migration or disappearance.",
        source_conflicts=[{
            "field": "description",
            "summary": "The current Gladly homepage is headed 'Commerce AI for every customer moment' and a company pricing-comparison blog labels Gladly product pricing 'Custom (sales-led)', while the developer API docs describe customer-service profiles and conversations.",
            "resolution": "All are first-party Gladly pages. This batch uses the developer reference for the documented API surface and preserves current branding/commercial context. The blog's product-level Custom (sales-led) label does not establish an API-specific plan entitlement; no migration, API removal, or replacement relationship is inferred."
        }],
    ),
]

traces = [
    {
        "app_id": 11, "research_tool": "Arena web_search + fetch_page",
        "queries": [
            "Zendesk developer API authentication API token OAuth pricing free trial MCP server official docs",
            "site:developer.zendesk.com MCP Zendesk official server AI MCP",
            "site:developer.zendesk.com/api-reference rate limits Zendesk ticketing API product features",
        ],
        "search_results": [{"query": "site:developer.zendesk.com MCP Zendesk official server AI MCP", "status": "OK", "results": 0}],
        "sources": [
            src("Security and authentication | Zendesk Developer Docs", "https://developer.zendesk.com/api-reference/introduction/security-and-auth/", "Verified-user requirement; OAuth Bearer token, global OAuth rule for public apps, deprecated Basic API tokens."),
            src("Ticketing | Zendesk Developer Docs", "https://developer.zendesk.com/api-reference/ticketing/introduction/", "Support API covers tickets, users, organizations, custom objects, and ticket workflows."),
            src("Zendesk Pricing Plans | Starting from $19/month", "https://www.zendesk.com/pricing/", "Opened current Support/Suite pricing page; free-trial signup is listed but API plan entitlement is not mapped."),
        ],
        "limitations": ["The MCP search was bounded to official developer-domain search plus the opened API/auth references; no complete Zendesk repository or Marketplace audit was made."],
    },
    {
        "app_id": 12, "research_tool": "Arena web_search + fetch_page",
        "queries": [
            "Intercom developer API authentication OAuth access token pricing trial MCP server official documentation",
            "site:developers.intercom.com/docs MCP server official Intercom pricing trial API access",
            "site:developers.intercom.com/docs/guides/mcp Intercom MCP available regions tools",
        ],
        "sources": [
            src("Authentication | Intercom and Fin Developer Platform", "https://developers.intercom.com/docs/build-an-integration/learn-more/authentication", "Private workspace Access Tokens vs public OAuth; Bearer request format and Developer Hub app flow."),
            src("Conversations | Intercom and Fin Developer Platform", "https://developers.intercom.com/docs/references/1.1/rest-api/conversations/conversations", "Conversation operations; access is only for apps with a trial or active subscription."),
            src("Model Context Protocol (MCP) | Intercom and Fin Developer Platform", "https://developers.intercom.com/docs/guides/mcp", "First-party hosted US/EU endpoints, 14 tools, permission checks; AU not supported."),
            src("Intercom Pricing | Plans for every team size", "https://www.intercom.com/pricing", "Self-serve trial and paid customer-service plans; pricing is seat plus usage based."),
        ],
        "limitations": ["No app, trial, API request, OAuth consent, or MCP session was executed; reference endpoint breadth beyond conversations was not exhaustively sampled."],
    },
    {
        "app_id": 13, "research_tool": "Arena web_search + fetch_page",
        "queries": [
            "Freshdesk developer REST API authentication API key pricing free trial MCP official docs",
            "site:developer.freshdesk.com/api authentication Freshdesk API key rate limits",
            "site:support.freshdesk.com Freshdesk API key Profile Settings verified agent current plan",
        ],
        "sources": [
            src("Freshdesk", "https://developer.freshdesk.com/api/", "Opened the API reference index; ticket, conversation, contact, agent, field/form, and other resource groups; Basic auth uses API key."),
            src("Model Context Protocol (MCP) integration in Freshdesk : Freshdesk Support", "https://support.freshdesk.com/support/solutions/articles/50000012670-model-context-protocol-mcp-integration-in-freshdesk", "Official MCP GA date, subdomain endpoint, API-key-only auth, supported plans, included actions/rate limits."),
            src("How To Find Your API Key : Freshdesk Support", "https://support.freshdesk.com/support/solutions/articles/215517-how-to-find-your-api-key", "Current support instructions: Profile Settings, CAPTCHA, verified agent, role-based API actions."),
            src("Where can I find my API key? : Freshdesk Support", "https://support.freshdesk.com/support/solutions/articles/225435-where-can-i-find-my-api-key-", "Current-plan table marks API key unavailable on Free and available on Growth/Pro/Enterprise; legacy plan rows are separate."),
            src("Freshdesk Customer Support Software Pricing & Plans | Freshworks", "https://www.freshworks.com/freshdesk/pricing/", "Opened Growth/Pro/Enterprise prices, self-serve trial links, and MCP action add-on pricing."),
        ],
        "limitations": ["No account, API key, production plan, or MCP action was tested; one plan article includes historical plan names which are not treated as current."],
    },
    {
        "app_id": 14, "research_tool": "Arena web_search + fetch_page",
        "queries": [
            "Front app API authentication API token OAuth pricing trial MCP official developer documentation",
            "site:dev.frontapp.com/docs MCP Front API free trial pricing official",
            "site:dev.frontapp.com/docs/authentication Front API public OAuth API tokens",
        ],
        "sources": [
            src("Welcome", "https://dev.frontapp.com/docs/welcome", "Free developer environment limited to three teammates; Core API CRUD/webhooks and related platform surfaces."),
            src("Authentication", "https://dev.frontapp.com/docs/authentication", "Bearer tokens from API tokens or OAuth; OAuth required for public integrations unless exception."),
            src("MCP Server", "https://dev.frontapp.com/docs/mcp-server", "First-party open-beta MCP endpoint, per-user OAuth, confidential client ID/secret, no DCR."),
            src("Partnering With Front", "https://dev.frontapp.com/docs/partnering-with-front", "Free developer-account path and separation between public partnerships and private/single-client use."),
        ],
        "limitations": ["No Front developer account, OAuth app, API token, or MCP client compatibility test was performed."],
    },
    {
        "app_id": 15, "research_tool": "Arena web_search + fetch_page",
        "queries": [
            "Pylon customer support API developer docs authentication API key OAuth MCP plan access official",
            "Pylon developer docs REST API authentication API tokens official docs Pylon pricing trial",
            "Pylon pricing free trial API plan access official usepylon.com",
            "site:docs.usepylon.com API authentication Pylon official",
        ],
        "sources": [
            src("API | Pylon", "https://docs.usepylon.com/pylon-docs/developer/api", "Official API page says Pylon API provides programmatic read/action access and only Admin users can create API tokens."),
            src("Authentication | Pylon", "https://docs.usepylon.com/pylon-docs/developer/api/authentication", "Bearer auth, US/EU API base URLs, /me check, token attribution."),
            src("API & Webhooks Integration | Pylon", "https://www.usepylon.com/integrations/api-webhooks", "First-party API/webhook product page lists accounts, contacts, issues, messages, tasks/projects, knowledge base, custom objects, and event delivery."),
            src("How do I create a Pylon API token? | Pylon Knowledge Base", "https://support.usepylon.com/articles/4735104435-how-do-i-create-an-api-token", "Admin-only token creation, Settings path, one-time token visibility, role selection."),
            src("How do I connect to the Pylon MCP Server? | Pylon Knowledge Base", "https://support.usepylon.com/articles/2407390554-connecting-to-the-pylon-mcp-server", "OAuth-only MCP, Member/Admin seat, user-scoped issue/account/contact tools; no API-key/machine auth."),
        ],
        "failures": [
            {"stage": "fetch_page", "url": "https://www.usepylon.com/pricing", "status": "REDIRECTED", "final_url": "https://www.usepylon.com/schedule-demo", "note": "Returned a required-field demo form rather than a pricing/plan table; no plan claim was taken from search snippets."},
            {"stage": "fetch_page", "url": "https://www.usepylon.com/pricing/", "status": "REDIRECTED", "final_url": "https://www.usepylon.com/schedule-demo", "note": "Same pricing-page redirect; plan/trial entitlement remains unresolved."},
            {"stage": "fetch_page", "url": "https://usepylon.com/pricing", "status": "REDIRECTED", "final_url": "https://www.usepylon.com/schedule-demo", "note": "Same demo-form destination; no plan/trial entitlement claim used."},
        ],
        "limitations": ["Public account signup, trial, API/MCP plan eligibility, and pricing were not established from opened pages."],
    },
    {
        "app_id": 16, "research_tool": "Arena web_search + fetch_page",
        "queries": [
            "LiveAgent API authentication REST API key pricing trial MCP official documentation",
            "site:support.liveagent.com API reference API token LiveAgent trial pricing MCP integration official docs",
            "LiveAgent MCP server OAuth 2.1 bearer API official support documentation",
        ],
        "sources": [
            src("MCP Integration for Agents", "https://support.liveagent.com/647358-MCP-Integration-for-Agents", "Current first-party MCP endpoint/auth, per-agent identity/permissions, audit trail, and AI-credit budget."),
            src("Complete API reference", "https://support.liveagent.com/840770-Complete-API-reference", "Public REST v1 reference lists conversations/messages, customers, companies, KB, reports, tags, files, and agents."),
            src("Pricing | LiveAgent - Help Desk Software & Live Chat", "https://www.liveagent.com/pricing/", "30-day no-card trial and paid per-agent tiers."),
        ],
        "limitations": ["Current API v3 documentation is exposed within a customer account and was not inspected; opened public API v1 documentation is older."],
    },
    {
        "app_id": 17, "research_tool": "Arena web_search + fetch_page",
        "queries": [
            "Plain customer support API official docs authentication OAuth API key pricing MCP server",
            "Plain API docs Machine Users API key GraphQL pricing launch plans official Plain documentation",
            "site:plain.com/docs GraphQL authentication machine users MCP server",
        ],
        "sources": [
            src("Introduction - Plain Docs", "https://www.plain.com/docs/graphql/introduction", "Official GraphQL endpoint/schema and customer query; product itself is built on the API."),
            src("Authentication - Plain Docs", "https://www.plain.com/docs/graphql/authentication", "Machine users, multi-key rotation, fine-grained permissions, one-time copy."),
            src("MCP server - Plain Docs", "https://www.plain.com/docs/integrations/mcp-server", "Official OAuth MCP endpoint, inherited permissions, required scopes, 30 tools."),
            src("Plain Pricing — Plans from $35/seat/month | 7-Day Free Trial", "https://www.plain.com/pricing", "Seven-day no-card trial and self-serve Foundation; API feature matrix extraction lacks clear per-plan mapping."),
        ],
        "failures": [
            {"stage": "fetch_page", "url": "https://www.plain.com/docs/api", "status": "HTTP_404", "note": "Noncanonical route returned Page Not Found; current GraphQL documentation was found through official search/docs index and opened."}
        ],
        "limitations": ["No Plain workspace/API token or MCP connection was used; API entitlement by plan is not fully legible in the opened pricing extraction."],
    },
    {
        "app_id": 18, "research_tool": "Arena web_search + fetch_page",
        "queries": [
            "Help Scout API authentication OAuth app key pricing trial MCP official developer docs",
            "site:developer.helpscout.com MCP official Help Scout API docs OAuth pricing trial access",
            "site:helpscout.com OR site:developer.helpscout.com MCP server Help Scout official",
        ],
        "sources": [
            src("Inbox API 2.0 | Help Scout Developers", "https://developer.helpscout.com/mailbox-api/", "HTTPS/JSON Inbox API v2 with OAuth2; links to resource endpoints and SDKs."),
            src("Authentication | Help Scout Developers", "https://developer.helpscout.com/mailbox-api/overview/authentication/", "Authorization Code/Client Credentials, Bearer tokens, My Apps path, active invited user requirement."),
            src("Help Scout Pricing: Affordable Customer Support Software", "https://www.helpscout.com/pricing/", "Free plan and paid Standard/Plus/Pro tiers with current seat pricing/features."),
            src("Connect your AI Agent to Help Scout via MCP - Help Scout Support", "https://docs.helpscout.com/article/1779-connect-your-ai-agent-with-help-scout-to-search-conversations-and-pull-reports", "Official MCP endpoint, Standard/Plus/Pro API entitlement, read-only behavior, reports/docs constraints."),
        ],
        "failures": [
            {"stage": "fetch_page", "url": "https://www.helpscout.com/blog/introducing-help-scout-mcp/", "status": "HTTP_404", "note": "The marketing-blog URL returned 404; the official support setup guide directly confirmed MCP status and access conditions."}
        ],
        "limitations": ["No Help Scout API key, OAuth app, or MCP connection was created; new MCP connections are read-only."],
    },
    {
        "app_id": 19, "research_tool": "Arena web_search + fetch_page",
        "queries": [
            "Gorgias REST API authentication API key OAuth pricing trial MCP official developer documentation",
            "site:developers.gorgias.com MCP official docs OAuth API pricing Helpdesk all plans",
            "site:gorgias.com/blog MCP Gorgias open beta mcp.gorgias.com",
        ],
        "sources": [
            src("Authentication", "https://developers.gorgias.com/reference/authentication", "Private app API key vs public OAuth2; OAuth2 mandatory for public apps."),
            src("Introduction", "https://developers.gorgias.com/reference/introduction", "Official REST/JSON API reference with resource-oriented URLs."),
            src("Access your Gorgias REST API credentials | Gorgias Help Center", "https://helpcenter.gorgias.com/en-US/rest-api-208286", "Owner/admin-created per-user API key, HTTP Basic credentials, all Helpdesk plans, full account-data access."),
            src("Gorgias Pricing – Build the customer support suite that fits your needs", "https://www.gorgias.com/pricing", "Paid plan tiers, free-trial signup, ticket and AI usage pricing."),
            src("How to Connect Gorgias to Claude or ChatGPT (6 Workflows to Try Right Now)", "https://www.gorgias.com/blog/gorgias-mcp", "First-party MCP endpoint mcp.gorgias.com/mcp?gorgias_subdomain=YOUR-SUBDOMAIN; OAuth; open beta for all paid plan customers; no extra cost within the Gorgias plan; an active AI-client subscription is separate."),
        ],
        "failures": [
            {"stage": "fetch_page", "url": "https://docs.gorgias.com/en-US/rest-api-208286", "status": "REDIRECTED", "final_url": "https://helpcenter.gorgias.com/en-US/rest-api-208286", "note": "The direct Help Center path is on helpcenter.gorgias.com; final page was opened and read."}
        ],
        "limitations": ["No Gorgias account, API key, public OAuth app, API call, or MCP session was used; individual endpoint groups were not exhaustively enumerated."],
    },
    {
        "app_id": 20, "research_tool": "Arena web_search + fetch_page",
        "queries": [
            "Gladly API authentication developer docs REST API pricing MCP official support integration",
            "site:developer.gladly.com MCP server Gladly API official docs pricing API access authentication",
            "site:developer.gladly.com OR site:gladly.ai MCP server Gladly official developer docs",
            "site:gladly.ai OR site:gladly.com API free trial MCP Gladly pricing access",
        ],
        "sources": [
            src("Gladly API", "https://developer.gladly.com/rest/", "Official REST API index enumerates customers, conversations, messages, agents, answers, reports, tasks, exports, and webhooks."),
            src("Setup and Testing", "https://help.gladly.com/developer-tutorials/docs/setup-and-testing", "API User permission, Basic API token flow, and sandbox purchasing/contact requirements."),
            src("Agentic commerce platform built for top brands | Gladly", "https://www.gladly.ai/", "Current official homepage says Commerce AI and offers Get a Demo/Try it yourself; no API plan/pricing entitlement is described."),
            src("What Freshdesk actually costs in 2026 | Gladly", "https://www.gladly.ai/blog/freshdesk-pricing/", "First-party comparison describes Gladly pricing as custom/sales-led; not used to infer specific API entitlements."),
        ],
        "search_results": [{"query": "site:developer.gladly.com MCP server Gladly API official docs pricing API access authentication", "status": "OK", "results": 0}],
        "failures": [
            {"stage": "fetch_page", "url": "https://www.gladly.ai/pricing", "status": "REDIRECTED", "final_url": "https://www.gladly.ai/", "note": "No pricing matrix was returned; public pricing/API entitlement remains unresolved."}
        ],
        "limitations": ["No Gladly tenant, API token, sandbox, API request, or MCP connection was available; no exhaustive first-party repository/catalog audit was completed.", "Current Gladly marketing copy and developer API description use different product positioning; their relationship was not established."],
    },
]

capture = {
    "capture_date": TODAY,
    "capture_method": "Manual source capture via Arena web_search and fetch_page. Search snippets were treated as discovery only; claim-level evidence refers to opened pages. No Tavily/OpenAI provider call, account signup, API call, or MCP session was used.",
    "traces": traces,
    "records": records,
}
out = ROOT / "data/evidence/support_batch_11_capture.json"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(capture, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"Wrote {len(records)} records and {len(traces)} traces to {out}")
