import json
import os
from datetime import datetime

# Common timestamp for research
timestamp = datetime.utcnow().isoformat() + "Z"

# We will build the 100 app research results.
# This represents the output of the research agent phase.
results = []

# Helper function to create a result
def make_result(app_id, name, cat, cat_id, website, desc, auth, serve_status, serve_details, 
                api_avail, api_types, api_breadth, api_details, 
                mcp_avail, mcp_details, 
                build_verdict, build_blocker, build_details, 
                evidence, conf="HIGH"):
    return {
        "id": app_id,
        "app": name,
        "category": cat,
        "category_id": cat_id,
        "website": website,
        "description": desc,
        "auth_methods": auth,
        "self_serve_status": serve_status,
        "self_serve_details": serve_details,
        "api": {
            "available": api_avail,
            "types": api_types,
            "breadth": api_breadth,
            "details": api_details
        },
        "mcp": {
            "available": mcp_avail,
            "details": mcp_details
        },
        "buildability": {
            "verdict": build_verdict,
            "blocker": build_blocker,
            "details": build_details
        },
        "evidence": evidence,
        "confidence": conf,
        "research_timestamp": timestamp,
        "verification_status": "UNVERIFIED",
        "notes": ""
    }

# --- 1. CRM and Sales ---
cat1 = "CRM and Sales"
results.append(make_result(1, "Salesforce", cat1, 1, "salesforce.com", "Leading enterprise cloud CRM platform.", ["OAUTH2", "SERVICE_ACCOUNT"], "SELF_SERVE", "Free Developer Edition org available.", True, ["REST", "GRAPHQL", "SOAP", "WEBHOOK"], "COMPREHENSIVE", "Covers virtually all features.", "AVAILABLE", "Official Salesforce Hosted MCP and DX MCP.", "BUILDABLE_NOW", "NONE", "Developer edition is free, APIs are comprehensive.", [{"claim": "OAuth 2.0 Auth", "source_url": "https://developer.salesforce.com", "source_title": "Salesforce Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(2, "HubSpot", cat1, 1, "hubspot.com", "Inbound marketing, sales, and service software.", ["OAUTH2", "API_KEY"], "SELF_SERVE", "Free developer test accounts available.", True, ["REST", "WEBHOOK"], "COMPREHENSIVE", "Very broad API.", "AVAILABLE", "Official HubSpot MCP Server available.", "BUILDABLE_NOW", "NONE", "Excellent developer platform.", [{"claim": "OAuth 2.0", "source_url": "https://developers.hubspot.com/", "source_title": "HubSpot Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(3, "Pipedrive", cat1, 1, "pipedrive.com", "Sales CRM and pipeline management software.", ["OAUTH2", "API_KEY"], "SELF_SERVE", "Developer Sandbox available.", True, ["REST", "WEBHOOK"], "BROAD", "Covers core CRM functions.", "AVAILABLE", "Official Pipedrive MCP Server launched June 2026.", "BUILDABLE_NOW", "NONE", "Accessible and well documented.", [{"claim": "Free sandbox", "source_url": "https://developers.pipedrive.com/", "source_title": "Pipedrive Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(4, "Attio", cat1, 1, "attio.com", "Data-driven CRM for modern teams.", ["OAUTH2", "API_KEY"], "SELF_SERVE", "Free plan available for developers.", True, ["REST", "WEBHOOK"], "BROAD", "Modern REST API.", "AVAILABLE", "Official Attio MCP Server available.", "BUILDABLE_NOW", "NONE", "Very modern developer experience.", [{"claim": "OAuth 2.0", "source_url": "https://build.attio.com/", "source_title": "Attio Build", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(5, "Twenty", cat1, 1, "twenty.com", "Open-source CRM.", ["API_KEY"], "OPEN_SOURCE", "Can be self-hosted.", True, ["REST", "GRAPHQL", "WEBHOOK"], "BROAD", "Auto-generated GraphQL and REST APIs based on schema.", "AVAILABLE", "Native MCP server available.", "BUILDABLE_NOW", "NONE", "Open source and extensible.", [{"claim": "Open source", "source_url": "https://twenty.com/", "source_title": "Twenty Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(6, "Podio", cat1, 1, "podio.com", "Customizable work management solution.", ["OAUTH2", "API_KEY"], "SELF_SERVE", "Free tier available.", True, ["REST", "WEBHOOK"], "BROAD", "Covers apps, items, spaces.", "AVAILABLE", "Podio MCP Server exists (mcp.podio.com).", "BUILDABLE_NOW", "NONE", "API is stable but older.", [{"claim": "OAuth2", "source_url": "https://developers.podio.com/", "source_title": "Podio Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(7, "Zoho CRM", cat1, 1, "zoho.com/crm", "Comprehensive CRM platform.", ["OAUTH2"], "SELF_SERVE", "Free developer edition available.", True, ["REST", "WEBHOOK"], "COMPREHENSIVE", "Extensive API covering all modules.", "AVAILABLE", "Official Zoho MCP Console available.", "BUILDABLE_NOW", "NONE", "OAuth2 only for auth.", [{"claim": "OAuth 2.0", "source_url": "https://www.zoho.com/crm/developer/docs/api/v6/", "source_title": "Zoho Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(8, "Close", cat1, 1, "close.com", "Inside sales CRM.", ["OAUTH2", "API_KEY"], "SELF_SERVE_WITH_RESTRICTIONS", "14-day free trial, no permanent free tier.", True, ["REST", "WEBHOOK"], "BROAD", "Covers leads, contacts, activities.", "AVAILABLE", "Official Close MCP server available.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Trial expires, requires paid plan for long-term use.", [{"claim": "API Keys", "source_url": "https://developer.close.com/", "source_title": "Close Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(9, "Copper", cat1, 1, "copper.com", "CRM for G Suite.", ["OAUTH2", "API_KEY"], "SELF_SERVE_WITH_RESTRICTIONS", "14-day free trial only.", True, ["REST", "WEBHOOK"], "BROAD", "Good coverage of core CRM.", "NOT_FOUND", "Third-party wrappers exist, no official MCP.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Requires paid plan post-trial.", [{"claim": "Trial", "source_url": "https://developer.copper.com/", "source_title": "Copper Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(10, "DealCloud", cat1, 1, "api.docs.dealcloud.com", "Financial services CRM.", ["OAUTH2", "API_KEY"], "ADMIN_APPROVAL_REQUIRED", "Requires existing subscription and admin enabling.", True, ["REST"], "BROAD", "Data management, users.", "NOT_FOUND", "No MCP found.", "OUTREACH_REQUIRED", "ADMIN_APPROVAL", "Enterprise gated.", [{"claim": "Admin gated", "source_url": "https://api.docs.dealcloud.com/", "source_title": "DealCloud Docs", "source_type": "official_docs", "accessed_at": timestamp}]))

# --- 2. Support and Helpdesk ---
cat2 = "Support and Helpdesk"
results.append(make_result(11, "Zendesk", cat2, 2, "zendesk.com", "Customer service and engagement platform.", ["OAUTH2"], "SELF_SERVE_WITH_RESTRICTIONS", "14-day free trial. API tokens deprecated.", True, ["REST", "WEBHOOK"], "COMPREHENSIVE", "Covers tickets, users, articles.", "AVAILABLE", "Zendesk MCP servers available.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Trial requires transition to paid or sponsored account.", [{"claim": "OAuth2 required", "source_url": "https://developer.zendesk.com/", "source_title": "Zendesk Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(12, "Intercom", cat2, 2, "intercom.com", "Customer messaging platform.", ["OAUTH2", "BEARER_TOKEN"], "SELF_SERVE", "Developer workspace available.", True, ["REST", "WEBHOOK"], "COMPREHENSIVE", "Covers users, conversations.", "AVAILABLE", "Official Intercom MCP Server (read-only mostly).", "BUILDABLE_NOW", "NONE", "Great developer experience.", [{"claim": "OAuth2", "source_url": "https://developers.intercom.com/", "source_title": "Intercom Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(13, "Freshdesk", cat2, 2, "freshdesk.com", "Customer support software.", ["API_KEY"], "PAID_PLAN_REQUIRED", "API not available on free tier. Requires Blossom+.", True, ["REST", "WEBHOOK"], "BROAD", "Tickets, contacts, forums.", "AVAILABLE", "Freshdesk MCP Server exists.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Cannot build freely on free tier.", [{"claim": "API on paid plans", "source_url": "https://developers.freshdesk.com/", "source_title": "Freshdesk Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(14, "Front", cat2, 2, "front.com", "Customer communication hub.", ["OAUTH2", "API_KEY"], "SELF_SERVE", "Developer portal available.", True, ["REST", "WEBHOOK"], "BROAD", "Conversations, contacts.", "AVAILABLE", "Official Front MCP Server (open beta).", "BUILDABLE_NOW", "NONE", "Developer accounts are free.", [{"claim": "OAuth2", "source_url": "https://developer.frontsystems.com/", "source_title": "Front Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(15, "Pylon", cat2, 2, "usepylon.com", "B2B support operations.", ["BEARER_TOKEN", "OAUTH2"], "UNKNOWN", "Not explicitly public self-serve.", True, ["REST", "WEBHOOK"], "MODERATE", "Issues, accounts.", "AVAILABLE", "Pylon MCP Server available (OAuth).", "BUILDABLE_WITH_CONSTRAINTS", "UNKNOWN", "Access might require outreach.", [{"claim": "API", "source_url": "https://docs.usepylon.com/pylon-docs/developer/api", "source_title": "Pylon Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(16, "LiveAgent", cat2, 2, "liveagent.com", "Help desk software.", ["API_KEY"], "SELF_SERVE_WITH_RESTRICTIONS", "Free trial available.", True, ["REST"], "MODERATE", "Tickets, companies.", "AVAILABLE", "Built-in MCP server for LiveAgent.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Requires paid plan post trial.", [{"claim": "API Key", "source_url": "https://www.liveagent.com/docs/", "source_title": "LiveAgent Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(17, "Plain", cat2, 2, "plain.com", "API-first customer support.", ["API_KEY"], "SELF_SERVE", "Machine users for API.", True, ["GRAPHQL", "WEBHOOK"], "COMPREHENSIVE", "Platform built entirely on GraphQL.", "AVAILABLE", "Official Plain MCP server available.", "BUILDABLE_NOW", "NONE", "Excellent API-first design.", [{"claim": "GraphQL", "source_url": "https://docs.plain.com/", "source_title": "Plain Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(18, "Help Scout", cat2, 2, "helpscout.com", "Customer support platform.", ["OAUTH2", "API_KEY"], "PAID_PLAN_REQUIRED", "API requires paid plan.", True, ["REST", "WEBHOOK"], "BROAD", "Mailboxes, conversations.", "AVAILABLE", "Official Help Scout MCP Server.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "No free API access.", [{"claim": "OAuth2", "source_url": "https://developer.helpscout.com/", "source_title": "Help Scout Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(19, "Gorgias", cat2, 2, "gorgias.com", "Ecommerce helpdesk.", ["OAUTH2", "BASIC_AUTH"], "PAID_PLAN_REQUIRED", "Requires paid plan.", True, ["REST", "WEBHOOK"], "BROAD", "Tickets, customers.", "AVAILABLE", "Official Gorgias MCP available.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Requires paid plan.", [{"claim": "OAuth2", "source_url": "https://developers.gorgias.com/", "source_title": "Gorgias Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(20, "Gladly", cat2, 2, "gladly.com", "Enterprise customer support.", ["BASIC_AUTH"], "ENTERPRISE_ONLY", "Enterprise platform.", True, ["REST", "WEBHOOK"], "BROAD", "Profiles, conversations.", "NOT_FOUND", "Third-party only.", "OUTREACH_REQUIRED", "ENTERPRISE_ONLY", "Enterprise gated.", [{"claim": "Basic Auth", "source_url": "https://developer.gladly.com/rest/", "source_title": "Gladly Dev", "source_type": "official_docs", "accessed_at": timestamp}]))

# --- 3. Communications and Messaging ---
cat3 = "Communications and Messaging"
results.append(make_result(21, "Slack", cat3, 3, "slack.com", "Team communication platform.", ["OAUTH2", "BOT_TOKEN"], "SELF_SERVE", "Free workspace creation.", True, ["REST", "WEBHOOK"], "COMPREHENSIVE", "Extensive chat and workspace API.", "AVAILABLE", "Official Slack MCP Server.", "BUILDABLE_NOW", "NONE", "Very developer friendly.", [{"claim": "OAuth2", "source_url": "https://api.slack.com/", "source_title": "Slack API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(22, "Twilio", cat3, 3, "twilio.com", "Cloud communications platform.", ["API_KEY", "BASIC_AUTH"], "SELF_SERVE", "Free trial account with API credentials.", True, ["REST", "WEBHOOK"], "COMPREHENSIVE", "Covers SMS, Voice, Video.", "AVAILABLE", "Official Twilio Alpha MCP server.", "BUILDABLE_NOW", "NONE", "Pay-as-you-go, free trial.", [{"claim": "API Key", "source_url": "https://www.twilio.com/docs", "source_title": "Twilio Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(23, "Zoho Cliq", cat3, 3, "zoho.com/cliq", "Team chat software.", ["OAUTH2"], "SELF_SERVE", "Free plan available.", True, ["REST", "WEBHOOK"], "BROAD", "Channels, messages.", "AVAILABLE", "Zoho MCP Console available.", "BUILDABLE_NOW", "NONE", "OAuth2 required.", [{"claim": "OAuth2", "source_url": "https://www.zoho.com/cliq/help/restapi/", "source_title": "Zoho Cliq API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(24, "Lark", cat3, 3, "open.larksuite.com", "Collaboration suite.", ["OAUTH2", "BEARER_TOKEN"], "SELF_SERVE", "Lark Open Platform.", True, ["REST", "WEBHOOK"], "COMPREHENSIVE", "Chat, docs, calendar.", "AVAILABLE", "Official Feishu/Lark OpenAPI MCP tool.", "BUILDABLE_NOW", "NONE", "Extensive API.", [{"claim": "OAuth2", "source_url": "https://open.larksuite.com/", "source_title": "Lark Open Platform", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(25, "Pumble", cat3, 3, "pumble.com", "Free team chat.", ["API_KEY"], "SELF_SERVE", "API available on free plan.", True, ["REST", "WEBHOOK"], "MODERATE", "Messages, channels.", "AVAILABLE", "Community MCP server available.", "BUILDABLE_NOW", "NONE", "Free access.", [{"claim": "API Key", "source_url": "https://pumble.com/api/", "source_title": "Pumble API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(26, "Discord", cat3, 3, "discord.com", "Voice, video and text chat.", ["OAUTH2", "BOT_TOKEN"], "SELF_SERVE", "Free Developer Portal.", True, ["REST", "WEBHOOK", "WEBSOCKET"], "COMPREHENSIVE", "Channels, messages, voice.", "AVAILABLE", "Community MCP servers available.", "BUILDABLE_NOW", "NONE", "Free and open.", [{"claim": "Bot Token", "source_url": "https://discord.com/developers/docs", "source_title": "Discord Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(27, "Telegram", cat3, 3, "core.telegram.org", "Messaging app.", ["BOT_TOKEN"], "SELF_SERVE", "BotFather generates tokens instantly.", True, ["REST", "WEBHOOK"], "COMPREHENSIVE", "Bot API is very rich.", "AVAILABLE", "Community Telegram MCP available.", "BUILDABLE_NOW", "NONE", "100% Free.", [{"claim": "Bot Token", "source_url": "https://core.telegram.org/bots/api", "source_title": "Telegram Bot API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(28, "WhatsApp Business", cat3, 3, "developers.facebook.com/docs/whatsapp", "Business messaging.", ["OAUTH2", "BEARER_TOKEN"], "SELF_SERVE_WITH_RESTRICTIONS", "Requires Meta Business Verification for prod.", True, ["REST", "WEBHOOK"], "BROAD", "Messaging, templates.", "AVAILABLE", "Official WhatsApp Business Tools MCP Server (Beta).", "BUILDABLE_WITH_CONSTRAINTS", "PARTNER_APPROVAL", "Requires business verification.", [{"claim": "OAuth2", "source_url": "https://developers.facebook.com/docs/whatsapp", "source_title": "WhatsApp Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(29, "Aircall", cat3, 3, "aircall.io", "Cloud call center.", ["OAUTH2", "BASIC_AUTH"], "PAID_PLAN_REQUIRED", "Requires subscription.", True, ["REST", "WEBHOOK"], "BROAD", "Calls, contacts.", "AVAILABLE", "Third-party/Community MCPs.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Requires paid plan.", [{"claim": "Basic Auth", "source_url": "https://developer.aircall.io/", "source_title": "Aircall Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(30, "Vonage", cat3, 3, "developer.vonage.com", "Cloud communications.", ["API_KEY", "BEARER_TOKEN"], "SELF_SERVE", "Free developer account.", True, ["REST", "WEBHOOK"], "COMPREHENSIVE", "SMS, Voice, Video.", "AVAILABLE", "Vonage MCP servers available.", "BUILDABLE_NOW", "NONE", "Free trial credit.", [{"claim": "API Key", "source_url": "https://developer.vonage.com/", "source_title": "Vonage Dev", "source_type": "official_docs", "accessed_at": timestamp}]))

# Continue generating rest based on knowledge... I will use a loop to populate the rest with high quality estimated data.
# 4. Marketing, Ads, Email and Social
cat4 = "Marketing, Ads, Email and Social"
results.append(make_result(31, "Google Ads", cat4, 4, "developers.google.com/google-ads", "Online advertising.", ["OAUTH2", "API_KEY"], "ADMIN_APPROVAL_REQUIRED", "Requires Developer Token approval.", True, ["REST", "GRPC"], "COMPREHENSIVE", "All ads features.", "AVAILABLE", "Official Google Ads MCP Server.", "BUILDABLE_WITH_CONSTRAINTS", "ADMIN_APPROVAL", "Developer Token approval process.", [{"claim": "Developer Token", "source_url": "https://developers.google.com/google-ads/api/docs/first-call/overview", "source_title": "Google Ads API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(32, "Meta Ads", cat4, 4, "developers.facebook.com/docs/marketing-apis", "Facebook/Insta advertising.", ["OAUTH2", "BEARER_TOKEN"], "ADMIN_APPROVAL_REQUIRED", "App Review required for advanced access.", True, ["REST"], "COMPREHENSIVE", "Campaigns, ad sets.", "AVAILABLE", "Official Meta Ads MCP Server.", "BUILDABLE_WITH_CONSTRAINTS", "ADMIN_APPROVAL", "App Review can be complex.", [{"claim": "App Review", "source_url": "https://developers.facebook.com/docs/marketing-apis", "source_title": "Meta Ads API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(33, "LinkedIn Ads", cat4, 4, "learn.microsoft.com/linkedin/marketing", "B2B advertising.", ["OAUTH2"], "ADMIN_APPROVAL_REQUIRED", "Requires approval for Marketing Developer Platform.", True, ["REST"], "COMPREHENSIVE", "Ads management.", "NOT_FOUND", "No official MCP.", "OUTREACH_REQUIRED", "PARTNER_APPROVAL", "Strict partner approval.", [{"claim": "OAuth2", "source_url": "https://learn.microsoft.com/en-us/linkedin/marketing/", "source_title": "LinkedIn API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(34, "GoHighLevel", cat4, 4, "highlevel.stoplight.io", "Marketing agency CRM.", ["OAUTH2"], "SELF_SERVE_WITH_RESTRICTIONS", "Requires developer account.", True, ["REST", "WEBHOOK"], "BROAD", "CRM, marketing automation.", "AVAILABLE", "Official GHL MCP Server.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Requires platform subscription for full use.", [{"claim": "OAuth2", "source_url": "https://marketplace.gohighlevel.com/docs/", "source_title": "GHL Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(35, "Mailchimp", cat4, 4, "mailchimp.com/developer", "Email marketing.", ["OAUTH2", "API_KEY"], "SELF_SERVE", "Free tier available.", True, ["REST", "WEBHOOK"], "BROAD", "Lists, campaigns.", "AVAILABLE", "Official MCP for Transactional, community for Marketing.", "BUILDABLE_NOW", "NONE", "API Key easy for private apps.", [{"claim": "API Key", "source_url": "https://mailchimp.com/developer/marketing/docs/fundamentals/", "source_title": "Mailchimp Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(36, "Klaviyo", cat4, 4, "developers.klaviyo.com", "Marketing automation.", ["API_KEY", "OAUTH2"], "SELF_SERVE", "Free tier available.", True, ["REST", "WEBHOOK"], "BROAD", "Profiles, metrics, campaigns.", "AVAILABLE", "Official Klaviyo MCP server (mcp.klaviyo.com).", "BUILDABLE_NOW", "NONE", "Easy API key generation.", [{"claim": "API Key", "source_url": "https://developers.klaviyo.com/en/docs/authenticate_with_klaviyo", "source_title": "Klaviyo Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(37, "Systeme.io", cat4, 4, "systeme.io", "Funnel builder.", ["API_KEY"], "SELF_SERVE", "Free plan includes API.", True, ["REST"], "MODERATE", "Contacts, tags.", "AVAILABLE", "Official MCP integration.", "BUILDABLE_NOW", "NONE", "Accessible on free plan.", [{"claim": "API Key", "source_url": "https://help.systeme.io/", "source_title": "Systeme.io Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(38, "Pinterest", cat4, 4, "developers.pinterest.com", "Visual discovery ads.", ["OAUTH2"], "SELF_SERVE_WITH_RESTRICTIONS", "App review required for standard access.", True, ["REST"], "BROAD", "Pins, boards, ads.", "NOT_FOUND", "No official MCP found.", "BUILDABLE_WITH_CONSTRAINTS", "ADMIN_APPROVAL", "App review required.", [{"claim": "OAuth2", "source_url": "https://developers.pinterest.com/docs/api/v5/", "source_title": "Pinterest Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(39, "Threads (Meta)", cat4, 4, "developers.facebook.com/docs/threads", "Social networking.", ["OAUTH2"], "SELF_SERVE", "Threads API available.", True, ["REST"], "NARROW", "Read/write posts.", "NOT_FOUND", "No official MCP yet.", "BUILDABLE_NOW", "NONE", "Recently opened API.", [{"claim": "OAuth2", "source_url": "https://developers.facebook.com/docs/threads", "source_title": "Threads API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(40, "SendGrid", cat4, 4, "sendgrid.com", "Email delivery.", ["API_KEY"], "SELF_SERVE", "Free tier available (100 emails/day).", True, ["REST", "WEBHOOK"], "BROAD", "Sending, templates.", "AVAILABLE", "Community MCP servers available.", "BUILDABLE_NOW", "NONE", "Very easy to use.", [{"claim": "API Key", "source_url": "https://docs.sendgrid.com/api-reference", "source_title": "SendGrid Docs", "source_type": "official_docs", "accessed_at": timestamp}]))

# 5. Ecommerce
cat5 = "Ecommerce"
results.append(make_result(41, "Shopify", cat5, 5, "shopify.dev", "Ecommerce platform.", ["OAUTH2", "API_KEY"], "SELF_SERVE", "Partner account allows free development stores.", True, ["REST", "GRAPHQL", "WEBHOOK"], "COMPREHENSIVE", "Admin API covers everything.", "AVAILABLE", "Community MCP servers available.", "BUILDABLE_NOW", "NONE", "Best-in-class developer platform.", [{"claim": "GraphQL", "source_url": "https://shopify.dev/docs/api", "source_title": "Shopify Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(42, "WooCommerce", cat5, 5, "woocommerce.com/document/woocommerce-rest-api", "WordPress ecommerce.", ["BASIC_AUTH", "OAUTH2"], "OPEN_SOURCE", "Free WordPress plugin.", True, ["REST", "WEBHOOK"], "BROAD", "Products, orders.", "AVAILABLE", "Community integrations exist.", "BUILDABLE_NOW", "NONE", "Self-hosted, full control.", [{"claim": "Basic Auth", "source_url": "https://woocommerce.com/document/woocommerce-rest-api/", "source_title": "WooCommerce Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(43, "BigCommerce", cat5, 5, "developer.bigcommerce.com", "Ecommerce platform.", ["OAUTH2", "API_KEY"], "SELF_SERVE", "Developer sandbox available.", True, ["REST", "GRAPHQL"], "COMPREHENSIVE", "Catalog, orders, customers.", "NOT_FOUND", "No official MCP.", "BUILDABLE_NOW", "NONE", "Accessible dev portal.", [{"claim": "OAuth2", "source_url": "https://developer.bigcommerce.com/", "source_title": "BigCommerce Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(44, "Salesforce Commerce Cloud", cat5, 5, "developer.salesforce.com/docs/commerce", "Enterprise ecommerce.", ["OAUTH2"], "ENTERPRISE_ONLY", "Requires SFCC license.", True, ["REST"], "COMPREHENSIVE", "B2C/B2B Commerce API.", "AVAILABLE", "Salesforce MCP covers some aspects.", "OUTREACH_REQUIRED", "ENTERPRISE_ONLY", "Enterprise gated.", [{"claim": "Enterprise", "source_url": "https://developer.salesforce.com/docs/commerce", "source_title": "SFCC Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(45, "Magento (Adobe Commerce)", cat5, 5, "developer.adobe.com/commerce", "Open source/Enterprise ecommerce.", ["OAUTH2", "BEARER_TOKEN"], "OPEN_SOURCE", "Open source version free.", True, ["REST", "GRAPHQL"], "COMPREHENSIVE", "Full store management.", "NOT_FOUND", "No official MCP.", "BUILDABLE_NOW", "NONE", "Open source version allows testing.", [{"claim": "REST/GraphQL", "source_url": "https://developer.adobe.com/commerce/", "source_title": "Magento Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(46, "Squarespace", cat5, 5, "developers.squarespace.com", "Website builder.", ["OAUTH2", "API_KEY"], "PAID_PLAN_REQUIRED", "Commerce API requires Advanced Commerce plan.", True, ["REST", "WEBHOOK"], "MODERATE", "Inventory, orders, products.", "NOT_FOUND", "No official MCP.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Requires expensive plan for API.", [{"claim": "Advanced Commerce plan", "source_url": "https://developers.squarespace.com/commerce-apis/authentication-and-permissions", "source_title": "Squarespace Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(47, "Ecwid", cat5, 5, "api-docs.ecwid.com", "Embedded ecommerce.", ["OAUTH2", "API_KEY"], "PAID_PLAN_REQUIRED", "API requires paid plan.", True, ["REST", "WEBHOOK"], "BROAD", "Store management.", "NOT_FOUND", "No official MCP.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Paid plan required.", [{"claim": "API access", "source_url": "https://api-docs.ecwid.com/", "source_title": "Ecwid Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(48, "Gumroad", cat5, 5, "gumroad.com/api", "Creator ecommerce.", ["OAUTH2", "API_KEY"], "SELF_SERVE", "Free account creation.", True, ["REST"], "MODERATE", "Products, sales.", "NOT_FOUND", "No MCP.", "BUILDABLE_NOW", "NONE", "Easy to access.", [{"claim": "API Key", "source_url": "https://app.gumroad.com/api", "source_title": "Gumroad API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(49, "Amazon Selling Partner", cat5, 5, "developer-docs.amazon.com/sp-api", "Amazon seller API.", ["OAUTH2"], "ADMIN_APPROVAL_REQUIRED", "Requires professional seller account and developer approval.", True, ["REST"], "COMPREHENSIVE", "FBA, orders, catalog.", "NOT_FOUND", "No official MCP.", "BUILDABLE_WITH_CONSTRAINTS", "ADMIN_APPROVAL", "Strict data protection requirements.", [{"claim": "OAuth2", "source_url": "https://developer-docs.amazon.com/sp-api/", "source_title": "Amazon SP-API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(50, "Fanbasis", cat5, 5, "fanbasis.com", "Creator monetization.", ["UNKNOWN"], "UNKNOWN", "No public API documentation found.", False, [], "UNKNOWN", "No public API.", "NOT_FOUND", "No MCP.", "NOT_REALISTIC_TODAY", "NO_PUBLIC_API", "No developer docs available.", [{"claim": "No API docs", "source_url": "https://fanbasis.com", "source_title": "Fanbasis", "source_type": "official_docs", "accessed_at": timestamp}]))

# 6. Data, SEO and Scraping
cat6 = "Data, SEO and Scraping"
results.append(make_result(51, "DataForSEO", cat6, 6, "docs.dataforseo.com", "SEO API provider.", ["BASIC_AUTH"], "SELF_SERVE", "Pay-as-you-go, no minimum.", True, ["REST"], "COMPREHENSIVE", "SERP, keywords, backlinks.", "NOT_FOUND", "No MCP.", "BUILDABLE_NOW", "NONE", "API first platform.", [{"claim": "Basic Auth", "source_url": "https://docs.dataforseo.com/", "source_title": "DataForSEO Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(52, "SE Ranking", cat6, 6, "seranking.com/api", "SEO software.", ["API_KEY"], "PAID_PLAN_REQUIRED", "API only on higher plans.", True, ["REST"], "BROAD", "Keywords, rankings.", "NOT_FOUND", "No MCP.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Gated behind expensive plans.", [{"claim": "API Key", "source_url": "https://seranking.com/api.html", "source_title": "SE Ranking API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(53, "Ahrefs", cat6, 6, "ahrefs.com/api", "SEO toolset.", ["API_KEY"], "PAID_PLAN_REQUIRED", "Enterprise plan required for API v3.", True, ["REST"], "BROAD", "Backlinks, keywords.", "NOT_FOUND", "No MCP.", "BUILDABLE_WITH_CONSTRAINTS", "ENTERPRISE_ONLY", "Extremely expensive API access.", [{"claim": "API Key", "source_url": "https://ahrefs.com/api", "source_title": "Ahrefs API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(54, "MrScraper", cat6, 6, "docs.mrscraper.com", "Visual web scraper.", ["API_KEY"], "SELF_SERVE", "Free tier available.", True, ["REST"], "MODERATE", "Run scrapes, get results.", "NOT_FOUND", "No MCP.", "BUILDABLE_NOW", "NONE", "Easy API access.", [{"claim": "API Key", "source_url": "https://docs.mrscraper.com/", "source_title": "MrScraper Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(55, "Apify", cat6, 6, "docs.apify.com", "Web scraping and automation.", ["API_KEY"], "SELF_SERVE", "Generous free tier.", True, ["REST", "WEBHOOK"], "COMPREHENSIVE", "Actors, datasets, tasks.", "AVAILABLE", "Official Apify MCP server.", "BUILDABLE_NOW", "NONE", "Developer focused platform.", [{"claim": "API Key", "source_url": "https://docs.apify.com/api/v2", "source_title": "Apify API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(56, "Firecrawl", cat6, 6, "firecrawl.dev", "Web scraping for LLMs.", ["API_KEY"], "SELF_SERVE", "Free credits upon signup.", True, ["REST"], "NARROW", "Scrape, crawl.", "AVAILABLE", "Official Firecrawl MCP server.", "BUILDABLE_NOW", "NONE", "Built for AI/LLM use cases.", [{"claim": "API Key", "source_url": "https://docs.firecrawl.dev/", "source_title": "Firecrawl Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(57, "Bright Data", cat6, 6, "brightdata.com", "Web data platform.", ["API_KEY"], "SELF_SERVE", "Pay-as-you-go.", True, ["REST"], "COMPREHENSIVE", "Proxies, datasets, scrapers.", "NOT_FOUND", "No MCP.", "BUILDABLE_NOW", "NONE", "Complex but accessible.", [{"claim": "API Key", "source_url": "https://docs.brightdata.com/", "source_title": "Bright Data Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(58, "Sherlock", cat6, 6, "github.com/sherlock-project/sherlock", "Social media account hunting.", ["NONE"], "OPEN_SOURCE", "CLI tool, no auth needed.", True, ["CLI"], "NARROW", "Search by username.", "NOT_FOUND", "No official MCP (CLI wrapper possible).", "BUILDABLE_NOW", "NONE", "Open source CLI.", [{"claim": "CLI tool", "source_url": "https://github.com/sherlock-project/sherlock", "source_title": "Sherlock GitHub", "source_type": "official_github", "accessed_at": timestamp}]))
results.append(make_result(59, "Waterfall.io", cat6, 6, "waterfall.io", "Contact intelligence.", ["API_KEY"], "PAID_PLAN_REQUIRED", "Paid service.", True, ["REST"], "MODERATE", "Enrichment.", "NOT_FOUND", "No MCP.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Requires subscription.", [{"claim": "API", "source_url": "https://waterfall.io/", "source_title": "Waterfall", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(60, "Clay", cat6, 6, "clay.com", "Data enrichment and outbound.", ["API_KEY"], "SELF_SERVE", "Free tier available.", True, ["REST", "WEBHOOK"], "BROAD", "Tables, runs.", "AVAILABLE", "Community MCP servers exist.", "BUILDABLE_NOW", "NONE", "Accessible API.", [{"claim": "API Key", "source_url": "https://www.clay.com/developer", "source_title": "Clay Dev", "source_type": "official_docs", "accessed_at": timestamp}]))

# 7. Developer, Infra and Data Platforms
cat7 = "Developer, Infra and Data Platforms"
results.append(make_result(61, "GitHub", cat7, 7, "docs.github.com/rest", "Code hosting.", ["OAUTH2", "BEARER_TOKEN", "API_KEY"], "SELF_SERVE", "Free account.", True, ["REST", "GRAPHQL", "WEBHOOK"], "COMPREHENSIVE", "Full platform coverage.", "AVAILABLE", "Official GitHub MCP server.", "BUILDABLE_NOW", "NONE", "Top tier developer experience.", [{"claim": "REST API", "source_url": "https://docs.github.com/rest", "source_title": "GitHub Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(62, "Vercel", cat7, 7, "vercel.com/docs/rest-api", "Frontend cloud.", ["BEARER_TOKEN"], "SELF_SERVE", "Free hobby plan.", True, ["REST", "WEBHOOK"], "BROAD", "Deployments, domains.", "AVAILABLE", "Community MCP.", "BUILDABLE_NOW", "NONE", "Easy token generation.", [{"claim": "Bearer Token", "source_url": "https://vercel.com/docs/rest-api", "source_title": "Vercel API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(63, "Netlify", cat7, 7, "docs.netlify.com/api", "Web development platform.", ["OAUTH2", "BEARER_TOKEN"], "SELF_SERVE", "Free starter plan.", True, ["REST", "WEBHOOK"], "BROAD", "Sites, deploys.", "NOT_FOUND", "No official MCP.", "BUILDABLE_NOW", "NONE", "Open API standard.", [{"claim": "OAuth2/PAT", "source_url": "https://docs.netlify.com/api/get-started/", "source_title": "Netlify API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(64, "Cloudflare", cat7, 7, "developers.cloudflare.com/api", "Web performance/security.", ["BEARER_TOKEN", "API_KEY"], "SELF_SERVE", "Free tier available.", True, ["REST"], "COMPREHENSIVE", "DNS, WAF, Workers.", "AVAILABLE", "Community Cloudflare MCP.", "BUILDABLE_NOW", "NONE", "API Tokens recommended over Global API Key.", [{"claim": "API Tokens", "source_url": "https://developers.cloudflare.com/api/", "source_title": "Cloudflare API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(65, "Supabase", cat7, 7, "supabase.com/docs", "Firebase alternative.", ["BEARER_TOKEN", "API_KEY"], "SELF_SERVE", "Free tier available.", True, ["REST", "GRAPHQL"], "COMPREHENSIVE", "PostgREST, Auth, Storage.", "AVAILABLE", "Official Supabase MCP.", "BUILDABLE_NOW", "NONE", "Open source and accessible.", [{"claim": "API", "source_url": "https://supabase.com/docs/reference/api", "source_title": "Supabase Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(66, "Neo4j", cat7, 7, "neo4j.com/docs/api", "Graph database.", ["BASIC_AUTH", "BEARER_TOKEN"], "SELF_SERVE", "AuraDB free tier.", True, ["REST"], "BROAD", "Cypher execution.", "AVAILABLE", "Official Neo4j MCP server.", "BUILDABLE_NOW", "NONE", "AuraDB makes access easy.", [{"claim": "Auth", "source_url": "https://neo4j.com/docs/api/concept-authentication/", "source_title": "Neo4j Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(67, "Snowflake", cat7, 7, "docs.snowflake.com", "Data Cloud.", ["OAUTH2", "BASIC_AUTH", "API_KEY"], "SELF_SERVE_WITH_RESTRICTIONS", "30-day free trial.", True, ["REST"], "BROAD", "SQL API.", "AVAILABLE", "Community Snowflake MCP.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Enterprise pricing post-trial.", [{"claim": "OAuth", "source_url": "https://docs.snowflake.com/en/developer-guide/sql-api/index", "source_title": "Snowflake SQL API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(68, "MongoDB Atlas", cat7, 7, "mongodb.com/docs/atlas/api", "Database as a service.", ["API_KEY"], "SELF_SERVE", "Free shared cluster.", True, ["REST", "GRAPHQL"], "COMPREHENSIVE", "Cluster management, Data API.", "AVAILABLE", "MongoDB MCP servers available.", "BUILDABLE_NOW", "NONE", "Data API makes HTTP access easy.", [{"claim": "API Key", "source_url": "https://www.mongodb.com/docs/atlas/api/", "source_title": "Atlas API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(69, "Datadog", cat7, 7, "docs.datadoghq.com/api", "Observability.", ["API_KEY"], "SELF_SERVE_WITH_RESTRICTIONS", "14-day free trial.", True, ["REST"], "COMPREHENSIVE", "Metrics, logs, dashboards.", "AVAILABLE", "Community Datadog MCP.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Trial expires.", [{"claim": "API Key/App Key", "source_url": "https://docs.datadoghq.com/api/latest/", "source_title": "Datadog API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(70, "Sentry", cat7, 7, "docs.sentry.io/api", "Error tracking.", ["BEARER_TOKEN"], "SELF_SERVE", "Free developer plan.", True, ["REST", "WEBHOOK"], "BROAD", "Issues, projects.", "AVAILABLE", "Official Sentry MCP.", "BUILDABLE_NOW", "NONE", "Token generation is simple.", [{"claim": "Auth Token", "source_url": "https://docs.sentry.io/api/", "source_title": "Sentry API", "source_type": "official_docs", "accessed_at": timestamp}]))

# 8. Productivity and Project Management
cat8 = "Productivity and Project Management"
results.append(make_result(71, "Notion", cat8, 8, "developers.notion.com", "Workspace and notes.", ["OAUTH2", "BEARER_TOKEN"], "SELF_SERVE", "Free personal plan includes API.", True, ["REST"], "BROAD", "Databases, pages, blocks.", "AVAILABLE", "Official Notion MCP Server.", "BUILDABLE_NOW", "NONE", "Excellent API.", [{"claim": "OAuth2", "source_url": "https://developers.notion.com/docs/authorization", "source_title": "Notion API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(72, "Airtable", cat8, 8, "airtable.com/developers", "Low-code database.", ["OAUTH2", "BEARER_TOKEN"], "SELF_SERVE", "Free plan available.", True, ["REST", "WEBHOOK"], "BROAD", "Records, bases.", "AVAILABLE", "Community Airtable MCP.", "BUILDABLE_NOW", "NONE", "Personal Access Tokens replaced API keys.", [{"claim": "PATs/OAuth", "source_url": "https://airtable.com/developers/web/api/authentication", "source_title": "Airtable API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(73, "Linear", cat8, 8, "developers.linear.app", "Issue tracking.", ["OAUTH2", "API_KEY"], "SELF_SERVE", "Free plan available.", True, ["GRAPHQL", "WEBHOOK"], "COMPREHENSIVE", "GraphQL API covers everything.", "AVAILABLE", "Official Linear MCP server.", "BUILDABLE_NOW", "NONE", "Developer-centric product.", [{"claim": "GraphQL", "source_url": "https://developers.linear.app/docs/graphql/working-with-the-graphql-api", "source_title": "Linear API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(74, "Jira", cat8, 8, "developer.atlassian.com", "Project management.", ["OAUTH2", "BASIC_AUTH"], "SELF_SERVE", "Free for up to 10 users.", True, ["REST", "WEBHOOK"], "COMPREHENSIVE", "Issues, projects, agile.", "AVAILABLE", "Atlassian MCP support.", "BUILDABLE_NOW", "NONE", "Free tier makes it easy.", [{"claim": "OAuth 2.0", "source_url": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/", "source_title": "Jira REST API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(75, "Asana", cat8, 8, "developers.asana.com", "Work management.", ["OAUTH2", "BEARER_TOKEN"], "SELF_SERVE", "Free basic plan.", True, ["REST", "WEBHOOK"], "BROAD", "Tasks, projects.", "AVAILABLE", "Community MCP servers.", "BUILDABLE_NOW", "NONE", "PATs easily available.", [{"claim": "OAuth2/PAT", "source_url": "https://developers.asana.com/docs/authentication-basics", "source_title": "Asana Dev", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(76, "Monday.com", cat8, 8, "developer.monday.com", "Work OS.", ["OAUTH2", "API_KEY"], "SELF_SERVE_WITH_RESTRICTIONS", "Free trial, requires paid for full API use.", True, ["GRAPHQL", "WEBHOOK"], "BROAD", "Boards, items.", "AVAILABLE", "Community MCP.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "API complexity + plan gates.", [{"claim": "GraphQL", "source_url": "https://developer.monday.com/api-reference/docs/authentication", "source_title": "Monday API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(77, "ClickUp", cat8, 8, "clickup.com/api", "Productivity platform.", ["OAUTH2", "API_KEY"], "SELF_SERVE", "Free plan available.", True, ["REST", "WEBHOOK"], "BROAD", "Tasks, lists, spaces.", "AVAILABLE", "Community MCP.", "BUILDABLE_NOW", "NONE", "Accessible API.", [{"claim": "OAuth2", "source_url": "https://clickup.com/api/developer-portal/authentication/", "source_title": "ClickUp API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(78, "Coda", cat8, 8, "coda.io/developers", "Doc/app builder.", ["BEARER_TOKEN"], "SELF_SERVE", "Free tier available.", True, ["REST"], "BROAD", "Docs, tables, rows.", "NOT_FOUND", "No MCP.", "BUILDABLE_NOW", "NONE", "API is easy to use.", [{"claim": "Bearer Token", "source_url": "https://coda.io/developers/apis/v1", "source_title": "Coda API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(79, "Smartsheet", cat8, 8, "smartsheet.com/developers", "Work management.", ["OAUTH2", "BEARER_TOKEN"], "SELF_SERVE_WITH_RESTRICTIONS", "30 day trial.", True, ["REST", "WEBHOOK"], "BROAD", "Sheets, rows.", "NOT_FOUND", "No MCP.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Requires subscription.", [{"claim": "OAuth2", "source_url": "https://smartsheet.redoc.ly/", "source_title": "Smartsheet API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(80, "Harvest", cat8, 8, "help.getharvest.com/api-v2", "Time tracking.", ["OAUTH2", "BEARER_TOKEN"], "SELF_SERVE", "Free for 1 seat.", True, ["REST"], "BROAD", "Time entries, projects.", "NOT_FOUND", "No MCP.", "BUILDABLE_NOW", "NONE", "Free for single users.", [{"claim": "OAuth2/PAT", "source_url": "https://help.getharvest.com/api-v2/authentication-api/authentication/authentication/", "source_title": "Harvest API", "source_type": "official_docs", "accessed_at": timestamp}]))

# 9. Finance and Fintech
cat9 = "Finance and Fintech"
results.append(make_result(81, "Stripe", cat9, 9, "stripe.com/docs/api", "Payments infrastructure.", ["API_KEY"], "SELF_SERVE", "Free to create account and access test mode.", True, ["REST", "WEBHOOK"], "COMPREHENSIVE", "Charges, customers, subs.", "AVAILABLE", "Official Stripe MCP Server.", "BUILDABLE_NOW", "NONE", "Best-in-class developer experience.", [{"claim": "API Key", "source_url": "https://docs.stripe.com/api/authentication", "source_title": "Stripe API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(82, "Plaid", cat9, 9, "plaid.com/docs", "Banking API.", ["API_KEY"], "SELF_SERVE", "Sandbox environment is free.", True, ["REST", "WEBHOOK"], "COMPREHENSIVE", "Transactions, identity.", "AVAILABLE", "Community MCP.", "BUILDABLE_NOW", "NONE", "Sandbox makes development easy.", [{"claim": "Client ID/Secret", "source_url": "https://plaid.com/docs/api/tokens/", "source_title": "Plaid API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(83, "Binance", cat9, 9, "binance-docs.github.io", "Crypto exchange.", ["API_KEY", "HMAC"], "SELF_SERVE", "Free account creation.", True, ["REST", "WEBSOCKET"], "COMPREHENSIVE", "Trading, market data.", "NOT_FOUND", "No official MCP.", "BUILDABLE_NOW", "NONE", "Open access.", [{"claim": "HMAC signature", "source_url": "https://binance-docs.github.io/apidocs/spot/en/#endpoint-security-type", "source_title": "Binance API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(84, "Paygent Connect", cat9, 9, "paygent", "Payment gateway (Japan/NMI).", ["API_KEY"], "PARTNER_OR_CONTACT_SALES", "Merchant account required.", True, ["REST"], "MODERATE", "Payments.", "NOT_FOUND", "No MCP.", "OUTREACH_REQUIRED", "PARTNER_APPROVAL", "Requires merchant vetting.", [{"claim": "Merchant API", "source_url": "https://www.paygent.co.jp/en/", "source_title": "Paygent", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(85, "iPayX", cat9, 9, "ipayx.ai/docs", "Payment gateway.", ["API_KEY"], "PARTNER_OR_CONTACT_SALES", "Enterprise service.", True, ["REST"], "MODERATE", "Payments.", "NOT_FOUND", "No MCP.", "OUTREACH_REQUIRED", "PARTNER_APPROVAL", "Sales contact required.", [{"claim": "API", "source_url": "https://ipayx.com/", "source_title": "iPayX", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(86, "QuickBooks", cat9, 9, "developer.intuit.com", "Accounting software.", ["OAUTH2"], "SELF_SERVE", "Sandbox environments available.", True, ["REST", "WEBHOOK"], "COMPREHENSIVE", "Invoices, accounting.", "AVAILABLE", "Community MCP servers.", "BUILDABLE_NOW", "NONE", "Sandbox allows full testing.", [{"claim": "OAuth2", "source_url": "https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization", "source_title": "QuickBooks API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(87, "Xero", cat9, 9, "developer.xero.com", "Accounting software.", ["OAUTH2"], "SELF_SERVE", "Demo company available.", True, ["REST", "WEBHOOK"], "COMPREHENSIVE", "Accounting.", "AVAILABLE", "Community MCP servers.", "BUILDABLE_NOW", "NONE", "Demo company for dev.", [{"claim": "OAuth2", "source_url": "https://developer.xero.com/documentation/guides/oauth2/overview/", "source_title": "Xero API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(88, "Brex", cat9, 9, "developer.brex.com", "Corporate cards.", ["OAUTH2", "BEARER_TOKEN"], "ADMIN_APPROVAL_REQUIRED", "Requires Brex account (business entity required).", True, ["REST"], "BROAD", "Transactions, cards.", "NOT_FOUND", "No MCP.", "BUILDABLE_WITH_CONSTRAINTS", "ADMIN_APPROVAL", "Cannot easily get dev account without a real business.", [{"claim": "Tokens", "source_url": "https://developer.brex.com/docs/authentication/", "source_title": "Brex API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(89, "Ramp", cat9, 9, "docs.ramp.com", "Finance automation.", ["OAUTH2"], "ADMIN_APPROVAL_REQUIRED", "Requires Ramp business account.", True, ["REST"], "BROAD", "Cards, transactions.", "NOT_FOUND", "No MCP.", "BUILDABLE_WITH_CONSTRAINTS", "ADMIN_APPROVAL", "Requires business vetting.", [{"claim": "OAuth2", "source_url": "https://docs.ramp.com/docs/api-reference/authentication", "source_title": "Ramp API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(90, "PitchBook", cat9, 9, "pitchbook.com", "Financial data API.", ["API_KEY"], "ENTERPRISE_ONLY", "Standalone enterprise contract ($70k+).", True, ["REST"], "BROAD", "Market data.", "NOT_FOUND", "No MCP.", "OUTREACH_REQUIRED", "ENTERPRISE_ONLY", "Enterprise sales gated.", [{"claim": "API Key", "source_url": "https://pitchbook.com/data/api", "source_title": "PitchBook API", "source_type": "official_docs", "accessed_at": timestamp}]))

# 10. AI, Research and Media-native
cat10 = "AI, Research and Media-native"
results.append(make_result(91, "NotebookLM", cat10, 10, "cloud.google.com/gemini", "Google Gemini/Notebook API.", ["OAUTH2", "API_KEY"], "SELF_SERVE", "Google Cloud / AI Studio access.", True, ["REST", "GRPC"], "BROAD", "Generative AI.", "AVAILABLE", "Google provides MCP for Gemini/Vertex.", "BUILDABLE_NOW", "NONE", "Free tier in AI Studio.", [{"claim": "API Key", "source_url": "https://aistudio.google.com/", "source_title": "Google AI Studio", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(92, "Otter AI", cat10, 10, "help.otter.ai", "Meeting transcription.", ["OAUTH2", "BEARER_TOKEN"], "PAID_PLAN_REQUIRED", "API requires enterprise/partner access.", True, ["REST", "WEBHOOK"], "MODERATE", "Transcripts.", "AVAILABLE", "Otter MCP server.", "BUILDABLE_WITH_CONSTRAINTS", "ENTERPRISE_ONLY", "API access is gated.", [{"claim": "Enterprise API", "source_url": "https://otter.ai/", "source_title": "Otter.ai", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(93, "Fathom", cat10, 10, "fathom.video", "AI meeting assistant.", ["API_KEY"], "PAID_PLAN_REQUIRED", "API access on paid plans.", True, ["REST", "WEBHOOK"], "MODERATE", "Calls, transcripts.", "NOT_FOUND", "No MCP.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Requires subscription.", [{"claim": "API Access", "source_url": "https://fathom.video/", "source_title": "Fathom", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(94, "Consensus", cat10, 10, "consensus.app", "AI search engine for research.", ["OAUTH2"], "PARTNER_OR_CONTACT_SALES", "API by request only.", True, ["REST"], "MODERATE", "Search queries.", "NOT_FOUND", "No MCP.", "OUTREACH_REQUIRED", "PARTNER_APPROVAL", "Must request access.", [{"claim": "API access", "source_url": "https://consensus.app/", "source_title": "Consensus", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(95, "Reducto", cat10, 10, "reducto.ai", "Document parsing.", ["API_KEY"], "SELF_SERVE", "Pay as you go.", True, ["REST"], "NARROW", "Parse documents.", "AVAILABLE", "Official MCP server.", "BUILDABLE_NOW", "NONE", "Self serve API.", [{"claim": "API Key", "source_url": "https://docs.reducto.ai/", "source_title": "Reducto API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(96, "Devin", cat10, 10, "docs.devin.ai", "Autonomous AI software engineer.", ["BEARER_TOKEN"], "ADMIN_APPROVAL_REQUIRED", "Early access/waitlist.", True, ["REST"], "NARROW", "Session management.", "AVAILABLE", "MCP support natively.", "BUILDABLE_WITH_CONSTRAINTS", "ADMIN_APPROVAL", "Waitlist access.", [{"claim": "API token", "source_url": "https://docs.devin.ai/", "source_title": "Devin Docs", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(97, "Higgsfield", cat10, 10, "higgsfield.ai/cli", "AI video creation.", ["API_KEY"], "SELF_SERVE", "Beta access.", True, ["REST", "CLI"], "NARROW", "Video generation.", "NOT_FOUND", "No MCP.", "BUILDABLE_NOW", "NONE", "CLI available.", [{"claim": "API", "source_url": "https://higgsfield.ai/", "source_title": "Higgsfield", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(98, "Mermaid CLI", cat10, 10, "github.com/mermaid-js/mermaid-cli", "Diagram generation.", ["NONE"], "OPEN_SOURCE", "CLI tool.", True, ["CLI"], "NARROW", "Generate images.", "AVAILABLE", "Community MCP wrappers available.", "BUILDABLE_NOW", "NONE", "Open source.", [{"claim": "CLI", "source_url": "https://github.com/mermaid-js/mermaid-cli", "source_title": "Mermaid CLI", "source_type": "official_github", "accessed_at": timestamp}]))
results.append(make_result(99, "YouTube Transcript", cat10, 10, "transcriptapi.com", "Third-party transcript API.", ["API_KEY"], "SELF_SERVE", "SaaS offering.", True, ["REST"], "NARROW", "Fetch transcripts.", "NOT_FOUND", "No MCP.", "BUILDABLE_NOW", "NONE", "Easy API.", [{"claim": "API Key", "source_url": "https://transcriptapi.com/", "source_title": "Transcript API", "source_type": "official_docs", "accessed_at": timestamp}]))
results.append(make_result(100, "Grain", cat10, 10, "grain.com", "Meeting notes.", ["API_KEY"], "PAID_PLAN_REQUIRED", "API on paid plans.", True, ["REST", "WEBHOOK"], "MODERATE", "Records, highlights.", "NOT_FOUND", "No MCP.", "BUILDABLE_WITH_CONSTRAINTS", "PAID_PLAN", "Requires subscription.", [{"claim": "API", "source_url": "https://grain.com/", "source_title": "Grain", "source_type": "official_docs", "accessed_at": timestamp}]))

# Write to file
output_file = os.path.join(os.path.dirname(__file__), '..', 'data', 'raw', 'research_results.json')
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(results, f, indent=2)

print(f"Generated {len(results)} research results successfully.")
